# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 316)
        Form.setMaximumSize(QtCore.QSize(1992, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.calendarWidget.setStyleSheet(" /*Tool button styles */\n"
"QCalendarWidget QToolButton {\n"
" \n"
"    height:40px;\n"
"    width:500px;\n"
"    color:white;\n"
"    font-size:20px;\n"
"    icon-size:56px,56px;\n"
"    background-color: #DFD880;\n"
" \n"
"}\n"
"\n"
"  /*normal days */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
" \n"
" \n"
"font-size:18px;\n"
"color: #444;\n"
"background-color: #80CCE1;\n"
"selection-background-color:rgb(64,64,64);\n"
"selection-color:rgb(0,255,0);\n"
"}\n"
"\n"
"  /* header row */\n"
"QCalendarWidget  QWidget{\n"
" \n"
"alternate-background-color: #FAFAFA;\n"
" \n"
"}")
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
