# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardEvento.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgEventoCard(object):
    def setupUi(self, wdgEventoCard):
        wdgEventoCard.setObjectName("wdgEventoCard")
        wdgEventoCard.resize(200, 312)
        wdgEventoCard.setMinimumSize(QtCore.QSize(200, 300))
        wdgEventoCard.setMaximumSize(QtCore.QSize(16777215, 600))
        wdgEventoCard.setStyleSheet("#frGrupoCard {\n"
"    background-color: #0e90ad;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgEventoCard)
        self.gridLayout.setObjectName("gridLayout")
        self.frGrupoCard = QtWidgets.QFrame(wdgEventoCard)
        self.frGrupoCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frGrupoCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frGrupoCard.setObjectName("frGrupoCard")
        self.lbDescricao = QtWidgets.QTextEdit(self.frGrupoCard)
        self.lbDescricao.setGeometry(QtCore.QRect(20, 76, 370, 100))
        self.lbDescricao.setMinimumSize(QtCore.QSize(0, 100))
        self.lbDescricao.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lbDescricao.setStyleSheet("#lbDescricao {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}")
        self.lbDescricao.setReadOnly(True)
        self.lbDescricao.setObjectName("lbDescricao")
        self.lbTituloCard = QtWidgets.QLabel(self.frGrupoCard)
        self.lbTituloCard.setGeometry(QtCore.QRect(20, 20, 370, 50))
        self.lbTituloCard.setMinimumSize(QtCore.QSize(0, 50))
        self.lbTituloCard.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbTituloCard.setFont(font)
        self.lbTituloCard.setStyleSheet("#lbTituloCard{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"    border: 0px;\n"
"    font-size: 16pt;\n"
"    font-family: Ubuntu;\n"
"    font-weight: bold;\n"
"}")
        self.lbTituloCard.setObjectName("lbTituloCard")
        self.gridLayout.addWidget(self.frGrupoCard, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(wdgEventoCard)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 97))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 97))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 97))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(wdgEventoCard)
        QtCore.QMetaObject.connectSlotsByName(wdgEventoCard)

    def retranslateUi(self, wdgEventoCard):
        _translate = QtCore.QCoreApplication.translate
        wdgEventoCard.setWindowTitle(_translate("wdgEventoCard", "Form"))
        self.lbDescricao.setPlaceholderText(_translate("wdgEventoCard", "DESCRIÇÃO"))
        self.lbTituloCard.setText(_translate("wdgEventoCard", "Titulo"))
        self.pushButton.setText(_translate("wdgEventoCard", "PushButton"))
        self.pushButton_2.setText(_translate("wdgEventoCard", "PushButton"))
        self.pushButton_3.setText(_translate("wdgEventoCard", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgEventoCard = QtWidgets.QWidget()
    ui = Ui_wdgEventoCard()
    ui.setupUi(wdgEventoCard)
    wdgEventoCard.show()
    sys.exit(app.exec_())
