# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardEvento.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgEventoCard(object):
    def setupUi(self, wdgEventoCard):
        wdgEventoCard.setObjectName("wdgEventoCard")
        wdgEventoCard.resize(564, 400)
        wdgEventoCard.setMinimumSize(QtCore.QSize(200, 400))
        wdgEventoCard.setMaximumSize(QtCore.QSize(16777215, 400))
        wdgEventoCard.setStyleSheet("#frGrupoCard {\n"
"    background-color: #0e90ad;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgEventoCard)
        self.gridLayout.setObjectName("gridLayout")
        self.frGrupoCard = QtWidgets.QFrame(wdgEventoCard)
        self.frGrupoCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frGrupoCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frGrupoCard.setObjectName("frGrupoCard")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frGrupoCard)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbTituloCard = QtWidgets.QLabel(self.frGrupoCard)
        self.lbTituloCard.setMinimumSize(QtCore.QSize(0, 50))
        self.lbTituloCard.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbTituloCard.setFont(font)
        self.lbTituloCard.setStyleSheet("#lbTituloCard{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"    border: 0px;\n"
"    font-size: 16pt;\n"
"    font-family: Ubuntu;\n"
"    font-weight: bold;\n"
"}")
        self.lbTituloCard.setObjectName("lbTituloCard")
        self.gridLayout_2.addWidget(self.lbTituloCard, 0, 0, 1, 1)
        self.lbDescricao = QtWidgets.QTextEdit(self.frGrupoCard)
        self.lbDescricao.setMinimumSize(QtCore.QSize(0, 100))
        self.lbDescricao.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbDescricao.setStyleSheet("#lbDescricao {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}")
        self.lbDescricao.setReadOnly(True)
        self.lbDescricao.setObjectName("lbDescricao")
        self.gridLayout_2.addWidget(self.lbDescricao, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frGrupoCard, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(wdgEventoCard)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbEditarEvento = QtWidgets.QPushButton(self.frame)
        self.pbEditarEvento.setMinimumSize(QtCore.QSize(0, 97))
        self.pbEditarEvento.setObjectName("pbEditarEvento")
        self.verticalLayout.addWidget(self.pbEditarEvento)
        self.pbEmailEvento = QtWidgets.QPushButton(self.frame)
        self.pbEmailEvento.setMinimumSize(QtCore.QSize(0, 97))
        self.pbEmailEvento.setObjectName("pbEmailEvento")
        self.verticalLayout.addWidget(self.pbEmailEvento)
        self.pbDeletarEvento = QtWidgets.QPushButton(self.frame)
        self.pbDeletarEvento.setMinimumSize(QtCore.QSize(0, 97))
        self.pbDeletarEvento.setObjectName("pbDeletarEvento")
        self.verticalLayout.addWidget(self.pbDeletarEvento)
        self.gridLayout.addWidget(self.frame, 1, 2, 1, 1)
        self.frInfosEdicoes = QtWidgets.QFrame(wdgEventoCard)
        self.frInfosEdicoes.setMinimumSize(QtCore.QSize(0, 100))
        self.frInfosEdicoes.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frInfosEdicoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfosEdicoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfosEdicoes.setObjectName("frInfosEdicoes")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frInfosEdicoes)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbHoraInicioEvento = QtWidgets.QLabel(self.frInfosEdicoes)
        self.lbHoraInicioEvento.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbHoraInicioEvento.setObjectName("lbHoraInicioEvento")
        self.gridLayout_3.addWidget(self.lbHoraInicioEvento, 1, 2, 1, 1)
        self.teHoraInicioEvento = QtWidgets.QTimeEdit(self.frInfosEdicoes)
        self.teHoraInicioEvento.setMinimumSize(QtCore.QSize(0, 0))
        self.teHoraInicioEvento.setObjectName("teHoraInicioEvento")
        self.gridLayout_3.addWidget(self.teHoraInicioEvento, 2, 2, 1, 1)
        self.deDataEvento = QtWidgets.QDateEdit(self.frInfosEdicoes)
        self.deDataEvento.setMinimumSize(QtCore.QSize(50, 0))
        self.deDataEvento.setObjectName("deDataEvento")
        self.gridLayout_3.addWidget(self.deDataEvento, 2, 0, 1, 1)
        self.pbCancelaUpdate = QtWidgets.QPushButton(self.frInfosEdicoes)
        self.pbCancelaUpdate.setObjectName("pbCancelaUpdate")
        self.gridLayout_3.addWidget(self.pbCancelaUpdate, 3, 2, 1, 1)
        self.lbDataEvento = QtWidgets.QLabel(self.frInfosEdicoes)
        self.lbDataEvento.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbDataEvento.setObjectName("lbDataEvento")
        self.gridLayout_3.addWidget(self.lbDataEvento, 1, 0, 1, 1)
        self.lbHoraFimEvento = QtWidgets.QLabel(self.frInfosEdicoes)
        self.lbHoraFimEvento.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbHoraFimEvento.setObjectName("lbHoraFimEvento")
        self.gridLayout_3.addWidget(self.lbHoraFimEvento, 1, 3, 1, 1)
        self.cbxDiaInteiro = QtWidgets.QComboBox(self.frInfosEdicoes)
        self.cbxDiaInteiro.setObjectName("cbxDiaInteiro")
        self.cbxDiaInteiro.addItem("")
        self.cbxDiaInteiro.addItem("")
        self.gridLayout_3.addWidget(self.cbxDiaInteiro, 2, 1, 1, 1)
        self.teHoraFimEvento = QtWidgets.QTimeEdit(self.frInfosEdicoes)
        self.teHoraFimEvento.setMinimumSize(QtCore.QSize(50, 0))
        self.teHoraFimEvento.setObjectName("teHoraFimEvento")
        self.gridLayout_3.addWidget(self.teHoraFimEvento, 2, 3, 1, 1)
        self.pbConfirmaUpdate = QtWidgets.QPushButton(self.frInfosEdicoes)
        self.pbConfirmaUpdate.setObjectName("pbConfirmaUpdate")
        self.gridLayout_3.addWidget(self.pbConfirmaUpdate, 3, 1, 1, 1)
        self.lbDiaInteiroEvento = QtWidgets.QLabel(self.frInfosEdicoes)
        self.lbDiaInteiroEvento.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbDiaInteiroEvento.setObjectName("lbDiaInteiroEvento")
        self.gridLayout_3.addWidget(self.lbDiaInteiroEvento, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frInfosEdicoes)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.frInfosEdicoes, 0, 0, 1, 2)

        self.retranslateUi(wdgEventoCard)
        QtCore.QMetaObject.connectSlotsByName(wdgEventoCard)

    def retranslateUi(self, wdgEventoCard):
        _translate = QtCore.QCoreApplication.translate
        wdgEventoCard.setWindowTitle(_translate("wdgEventoCard", "Form"))
        self.lbTituloCard.setText(_translate("wdgEventoCard", "Titulo"))
        self.lbDescricao.setPlaceholderText(_translate("wdgEventoCard", "DESCRIÇÃO"))
        self.pbEditarEvento.setText(_translate("wdgEventoCard", "Editar"))
        self.pbEmailEvento.setText(_translate("wdgEventoCard", "Email"))
        self.pbDeletarEvento.setText(_translate("wdgEventoCard", "Deletar"))
        self.lbHoraInicioEvento.setText(_translate("wdgEventoCard", "Início"))
        self.pbCancelaUpdate.setText(_translate("wdgEventoCard", "Cancelar"))
        self.lbDataEvento.setText(_translate("wdgEventoCard", "Data do Evento"))
        self.lbHoraFimEvento.setText(_translate("wdgEventoCard", "Fim"))
        self.cbxDiaInteiro.setItemText(0, _translate("wdgEventoCard", "Não"))
        self.cbxDiaInteiro.setItemText(1, _translate("wdgEventoCard", "Sim"))
        self.pbConfirmaUpdate.setText(_translate("wdgEventoCard", "Confirmar"))
        self.lbDiaInteiroEvento.setText(_translate("wdgEventoCard", "Dia Inteiro"))
        self.label.setText(_translate("wdgEventoCard", "Você esta no modo de edição"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgEventoCard = QtWidgets.QWidget()
    ui = Ui_wdgEventoCard()
    ui.setupUi(wdgEventoCard)
    wdgEventoCard.show()
    sys.exit(app.exec_())
