# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgConfig(object):
    def setupUi(self, wdgConfig):
        wdgConfig.setObjectName("wdgConfig")
        wdgConfig.resize(1092, 787)
        wdgConfig.setStyleSheet("/*-----------------------Labels------------------------------*/\n"
"\n"
"#lbTitulo {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lbDescricao {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(wdgConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frCabecalho = QtWidgets.QFrame(wdgConfig)
        self.frCabecalho.setMinimumSize(QtCore.QSize(0, 60))
        self.frCabecalho.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frCabecalho)
        self.horizontalLayout.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frTextoCabecalho = QtWidgets.QFrame(self.frCabecalho)
        self.frTextoCabecalho.setMinimumSize(QtCore.QSize(250, 0))
        self.frTextoCabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTextoCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTextoCabecalho.setObjectName("frTextoCabecalho")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frTextoCabecalho)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbTitulo = QtWidgets.QLabel(self.frTextoCabecalho)
        self.lbTitulo.setObjectName("lbTitulo")
        self.verticalLayout_2.addWidget(self.lbTitulo)
        self.lbDescricao = QtWidgets.QLabel(self.frTextoCabecalho)
        self.lbDescricao.setObjectName("lbDescricao")
        self.verticalLayout_2.addWidget(self.lbDescricao)
        self.horizontalLayout.addWidget(self.frTextoCabecalho)
        spacerItem = QtWidgets.QSpacerItem(524, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frCabecalho)
        self.tabWidget = QtWidgets.QTabWidget(wdgConfig)
        self.tabWidget.setObjectName("tabWidget")
        self.tabUsuario = QtWidgets.QWidget()
        self.tabUsuario.setObjectName("tabUsuario")
        self.tabWidget.addTab(self.tabUsuario, "")
        self.tabClientes = QtWidgets.QWidget()
        self.tabClientes.setObjectName("tabClientes")
        self.tabWidget.addTab(self.tabClientes, "")
        self.tabAgenda = QtWidgets.QWidget()
        self.tabAgenda.setObjectName("tabAgenda")
        self.tabWidget.addTab(self.tabAgenda, "")
        self.tabFinanceiro = QtWidgets.QWidget()
        self.tabFinanceiro.setObjectName("tabFinanceiro")
        self.tabWidget.addTab(self.tabFinanceiro, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(wdgConfig)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgConfig)

    def retranslateUi(self, wdgConfig):
        _translate = QtCore.QCoreApplication.translate
        wdgConfig.setWindowTitle(_translate("wdgConfig", "Form"))
        self.lbTitulo.setText(_translate("wdgConfig", "Configurações do usuário"))
        self.lbDescricao.setText(_translate("wdgConfig", "Nesta página você pode alterar as configurações referentes ao seu cadastro."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsuario), _translate("wdgConfig", "Usuário"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClientes), _translate("wdgConfig", "Clientes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAgenda), _translate("wdgConfig", "Agenda"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFinanceiro), _translate("wdgConfig", "Financeiro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgConfig = QtWidgets.QWidget()
    ui = Ui_wdgConfig()
    ui.setupUi(wdgConfig)
    wdgConfig.show()
    sys.exit(app.exec_())
