# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashAgenda1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgAgenda(object):
    def setupUi(self, wdgAgenda):
        wdgAgenda.setObjectName("wdgAgenda")
        wdgAgenda.resize(754, 700)
        self.gridLayout = QtWidgets.QGridLayout(wdgAgenda)
        self.gridLayout.setObjectName("gridLayout")
        self.frCompromisso = QtWidgets.QFrame(wdgAgenda)
        self.frCompromisso.setMinimumSize(QtCore.QSize(210, 0))
        self.frCompromisso.setStyleSheet("#frCompromisso{\n"
"background-color: transparent;\n"
"border-left: 3px dashed rgb(108, 251, 208);\n"
"border-right: 3px dashed rgb(108, 251, 208);\n"
"}")
        self.frCompromisso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCompromisso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCompromisso.setObjectName("frCompromisso")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frCompromisso)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbData = QtWidgets.QLabel(self.frCompromisso)
        self.lbData.setMinimumSize(QtCore.QSize(0, 50))
        self.lbData.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.lbData.setText("")
        self.lbData.setAlignment(QtCore.Qt.AlignCenter)
        self.lbData.setObjectName("lbData")
        self.gridLayout_2.addWidget(self.lbData, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frCompromisso)
        font = QtGui.QFont()
        font.setFamily("Fira Sans ExtraLight")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(108, 251, 208);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frCompromisso, 0, 3, 2, 1)
        self.frAgenda = QtWidgets.QFrame(wdgAgenda)
        self.frAgenda.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frAgenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frAgenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAgenda.setObjectName("frAgenda")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frAgenda)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vlAgenda = QtWidgets.QVBoxLayout()
        self.vlAgenda.setObjectName("vlAgenda")
        self.label_2 = QtWidgets.QLabel(self.frAgenda)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Fira Sans ExtraLight")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(108, 251, 208);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vlAgenda.addWidget(self.label_2)
        self.gridLayout_3.addLayout(self.vlAgenda, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frAgenda, 0, 2, 1, 1)

        self.retranslateUi(wdgAgenda)
        QtCore.QMetaObject.connectSlotsByName(wdgAgenda)

    def retranslateUi(self, wdgAgenda):
        _translate = QtCore.QCoreApplication.translate
        wdgAgenda.setWindowTitle(_translate("wdgAgenda", "Form"))
        self.label.setText(_translate("wdgAgenda", "Compromissos"))
        self.label_2.setText(_translate("wdgAgenda", "Agendamentos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgAgenda = QtWidgets.QWidget()
    ui = Ui_wdgAgenda()
    ui.setupUi(wdgAgenda)
    wdgAgenda.show()
    sys.exit(app.exec_())
