# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgCliente(object):
    def setupUi(self, wdgCliente):
        wdgCliente.setObjectName("wdgCliente")
        wdgCliente.resize(1094, 790)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgCliente.sizePolicy().hasHeightForWidth())
        wdgCliente.setSizePolicy(sizePolicy)
        wdgCliente.setStyleSheet("#wdgCliente {\n"
"    background-color: #80CCE1;\n"
"}\n"
"\n"
"/*------------------- Frame ---------------------*/\n"
"QFrame {\n"
"    background-color: #fafafa;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/*------------------- Label ---------------------*/\n"
"QLabel {\n"
"    font: 200 14pt \"Ubuntu\" ;\n"
"\n"
"    border-radius: 10px;\n"
"    border: 2px solid  #fff;\n"
"    color: rgb(100, 100, 100);\n"
"    background-color: #DFD880;\n"
"}\n"
"\n"
"#lbTitulo{\n"
"        background-color: none;\n"
"        font: 300 22pt \"Ubuntu\" ;\n"
"}\n"
"\n"
"#lbCorpo{\n"
"        background-color: none;\n"
"        font: 200 18pt \"Ubuntu\" ;\n"
"}\n"
"\n"
"/*------------------- Line Edit ---------------------*/\n"
"QLineEdit {\n"
"    border: none;\n"
"    background-color: #fafafa;\n"
"    border-bottom: 2px solid;\n"
"    border-color: rgb(14, 144, 173);\n"
"    border-radius: 0px;\n"
"    \n"
"    \n"
"    font: 80 14pt \"Ubuntu\" ;\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(223, 216, 128);\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"/*    border-radius: 10px;*/\n"
"}\n"
"\n"
"/*------------------- Push Buttom ---------------------*/\n"
"QPushButton{\n"
"    background-color: #DFD880;\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #80CCE1;\n"
"}\n"
"\n"
"#pbConfirmarAtualizacao {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(90, 190, 20);\n"
"    color: white;\n"
"}\n"
"\n"
"#pbConfirmarAtualizacao::hover {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    color: rgb(100, 200, 22);\n"
"    border: 2px solid rgb(100, 200, 22);\n"
"}\n"
"\n"
"\n"
"#pbCancelarEdicao {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgba(239, 41, 41, 100);\n"
"    color: white;\n"
"}\n"
"\n"
"#pbCancelarEdicao::hover {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    color: rgba(239, 41, 41, 100);\n"
"    border: 2px solid rgba(239, 41, 41, 100);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#pbEnviarEmail {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"\n"
"/*------------------- Table Widget ---------------------*/\n"
"\n"
"QTableWidget {\n"
"    padding: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font-family: Ubuntu\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgCliente)
        self.gridLayout.setContentsMargins(0, 9, 0, 30)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabsCliente = QtWidgets.QTabWidget(wdgCliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabsCliente.sizePolicy().hasHeightForWidth())
        self.tabsCliente.setSizePolicy(sizePolicy)
        self.tabsCliente.setStyleSheet("QTabWidget::pane {\n"
"    border-top: 3px solid;\n"
"}\n"
"\n"
"QTabWidget QStackedWidget > QWidget   \n"
"{    \n"
"    background-color: #fafafa;\n"
"}\n"
"\n"
"\n"
"/*-------------------------------------------------------------*/\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    font: 80 14pt \"Fira Sans\" ;\n"
"    height: 25px;\n"
"    width: 125px;\n"
" \n"
"    border: 1px double transparent;\n"
"    border-top-left-radius: 14px;\n"
"    border-top-right-radius: 14px;\n"
"\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #DFD880;\n"
"    \n"
"}\n"
"\n"
"")
        self.tabsCliente.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabsCliente.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabsCliente.setObjectName("tabsCliente")
        self.tbInfosCliente = QtWidgets.QWidget()
        self.tbInfosCliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbInfosCliente.sizePolicy().hasHeightForWidth())
        self.tbInfosCliente.setSizePolicy(sizePolicy)
        self.tbInfosCliente.setStyleSheet("/*#frInfoCliente {\n"
"    background-color: rgba(197, 207, 198, 80);\n"
"}*/\n"
"\n"
"/*-----------------------Frames------------------------------*/\n"
"#frInfoBairro, \n"
"#frInfoCep, \n"
"#frInfoNome, \n"
"#frInfoTel, \n"
"#frInfoEndereco,\n"
"#frInfoCep,\n"
"#frInfoComplemento,\n"
"#frInfoEmail,\n"
"#frInfoCpf,\n"
"#frInformacoes,\n"
"#frInfoConfirmar,\n"
"#frInfoMeioPag,\n"
"#frInfoTitulo {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#frInfoCliente {\n"
"    padding: 4px;\n"
"    background-color: rgb(14, 144, 173, 30);\n"
"}\n"
"\n"
"#frClientesTotal, #frClientesMensal, #frClientesAnuais {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(96, 32, 132, 33), stop:1 rgba(128, 182, 255, 138));\n"
"    border-radius: 12px;\n"
"    /*border: 5px solid;\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 30), stop:1 rgba(255, 255, 255, 0)); \n"
"    border-top-color: transparent;\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 30), stop:1 rgba(255, 255, 255, 0));\n"
"    border-right-color: transparent;*/\n"
"}\n"
"\n"
"\n"
"/*-----------------------LineEdit------------------------------*/\n"
"#leInfoBairro, \n"
"#leInfoCep, \n"
"#leInfoNome,\n"
"#leInfoSobrenome, \n"
"#leInfoTel, \n"
"#leInfoEndereco,\n"
"#leInfoCep,\n"
"#leInfoComplemento,\n"
"#leInfoEmail,\n"
"#leInfoCpf,\n"
"#leInformacoes {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"}\n"
"\n"
"\n"
"/*-----------------------CheckBox------------------------------*/\n"
"#cbInfoAtivo::indicator:unchecked {\n"
"    background-color: #fff;\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"#cbInfoAtivo {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"/*-----------------------Labels------------------------------*/\n"
"\n"
"#lbInfoTitulo, #lbTblGeralTitulo {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lbInfoDescricao, #lbTblGeralDescricao, #lbTituloTotal {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}\n"
"\n"
"#lbTituloTotal, #lbTituloMensal, #lbTituloAnual  {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"    color: white;\n"
"}\n"
"\n"
"#lbValorTotal, #lbValorMensal, #lbValorAnual  {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 32pt;\n"
"    font-style: italic;\n"
"    color: white;\n"
"}\n"
"\n"
"#lbEstTotal, #lbEstMensal, #lbEstAnual {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    color: rgb(78, 154, 6);\n"
"}")
        self.tbInfosCliente.setObjectName("tbInfosCliente")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tbInfosCliente)
        self.gridLayout_3.setContentsMargins(-1, 6, 18, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frClientsList = QtWidgets.QFrame(self.tbInfosCliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frClientsList.sizePolicy().hasHeightForWidth())
        self.frClientsList.setSizePolicy(sizePolicy)
        self.frClientsList.setMaximumSize(QtCore.QSize(900, 16777215))
        self.frClientsList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frClientsList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frClientsList.setObjectName("frClientsList")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frClientsList)
        self.gridLayout_5.setContentsMargins(10, 10, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tblClientes = QtWidgets.QTableWidget(self.frClientsList)
        self.tblClientes.setMinimumSize(QtCore.QSize(530, 0))
        self.tblClientes.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tblClientes.setStyleSheet("QHeaderView::section {\n"
"   \n"
"    background-color: #fafafa;\n"
"    padding-left: 4px;\n"
"    border: none;\n"
"    border-bottom: 2px solid;\n"
"    color: #444;\n"
"}\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: #DFD880;\n"
"\n"
"}\n"
"\n"
"QTableView {\n"
"    alternate-background-color: #ddd;\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #DFD880;\n"
"    color: #444;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
" \n"
"QScrollBar:vertical {\n"
"     border: 2px solid transparent;\n"
"     background: transparent;\n"
"     width: 15px;\n"
"     margin: 22px 4px 22px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: transparent;\n"
"     border-right: 2px solid;\n"
"     min-height:20px;\n"
" }\n"
"\n"
"\n"
"\n"
" QScrollBar::add-line:vertical {\n"
"     border-top: 2px solid grey;\n"
"     background: transparent;\n"
"     height: 20px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border-bottom: 2px solid grey;\n"
"     background: transparent;\n"
"     height: 20px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     width: 6px;\n"
"     height: 6px;\n"
"     background: white;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"")
        self.tblClientes.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.tblClientes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblClientes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tblClientes.setLineWidth(0)
        self.tblClientes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tblClientes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblClientes.setAlternatingRowColors(True)
        self.tblClientes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblClientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblClientes.setShowGrid(False)
        self.tblClientes.setGridStyle(QtCore.Qt.NoPen)
        self.tblClientes.setCornerButtonEnabled(False)
        self.tblClientes.setRowCount(0)
        self.tblClientes.setColumnCount(6)
        self.tblClientes.setObjectName("tblClientes")
        item = QtWidgets.QTableWidgetItem()
        self.tblClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        item.setFont(font)
        self.tblClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        item.setFont(font)
        self.tblClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        item.setFont(font)
        self.tblClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        item.setFont(font)
        self.tblClientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        item.setFont(font)
        self.tblClientes.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tblClientes)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(8)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tblClientes.horizontalHeader().setCascadingSectionResizes(True)
        self.tblClientes.horizontalHeader().setDefaultSectionSize(150)
        self.tblClientes.horizontalHeader().setMinimumSectionSize(100)
        self.tblClientes.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tblClientes, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.frTblGeralTitulo = QtWidgets.QFrame(self.frClientsList)
        self.frTblGeralTitulo.setMinimumSize(QtCore.QSize(0, 60))
        self.frTblGeralTitulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTblGeralTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTblGeralTitulo.setObjectName("frTblGeralTitulo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frTblGeralTitulo)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbTblGeralTitulo = QtWidgets.QLabel(self.frTblGeralTitulo)
        self.lbTblGeralTitulo.setMinimumSize(QtCore.QSize(60, 0))
        self.lbTblGeralTitulo.setObjectName("lbTblGeralTitulo")
        self.verticalLayout_8.addWidget(self.lbTblGeralTitulo)
        self.lbTblGeralDescricao = QtWidgets.QLabel(self.frTblGeralTitulo)
        self.lbTblGeralDescricao.setObjectName("lbTblGeralDescricao")
        self.verticalLayout_8.addWidget(self.lbTblGeralDescricao)
        self.gridLayout_5.addWidget(self.frTblGeralTitulo, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frClientsList, 2, 0, 1, 1)
        self.frListButtons = QtWidgets.QFrame(self.tbInfosCliente)
        self.frListButtons.setMinimumSize(QtCore.QSize(0, 60))
        self.frListButtons.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frListButtons.setStyleSheet("")
        self.frListButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frListButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frListButtons.setObjectName("frListButtons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frListButtons)
        self.gridLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frRightButtons = QtWidgets.QFrame(self.frListButtons)
        self.frRightButtons.setMinimumSize(QtCore.QSize(100, 0))
        self.frRightButtons.setMaximumSize(QtCore.QSize(160, 60))
        self.frRightButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frRightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frRightButtons.setObjectName("frRightButtons")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frRightButtons)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frRightButtons1 = QtWidgets.QFrame(self.frRightButtons)
        self.frRightButtons1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frRightButtons1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frRightButtons1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frRightButtons1.setObjectName("frRightButtons1")
        self.horizontalLayout_191 = QtWidgets.QHBoxLayout(self.frRightButtons1)
        self.horizontalLayout_191.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_191.setSpacing(16)
        self.horizontalLayout_191.setObjectName("horizontalLayout_191")
        self.pbExportar = QtWidgets.QPushButton(self.frRightButtons1)
        self.pbExportar.setObjectName("pbExportar")
        self.horizontalLayout_191.addWidget(self.pbExportar)
        self.horizontalLayout_19.addWidget(self.frRightButtons1)
        self.gridLayout_4.addWidget(self.frRightButtons, 1, 4, 1, 1)
        self.frNomeTabela = QtWidgets.QFrame(self.frListButtons)
        self.frNomeTabela.setMinimumSize(QtCore.QSize(190, 0))
        self.frNomeTabela.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frNomeTabela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frNomeTabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frNomeTabela.setObjectName("frNomeTabela")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frNomeTabela)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbNomeTabela = QtWidgets.QLabel(self.frNomeTabela)
        self.lbNomeTabela.setMinimumSize(QtCore.QSize(180, 30))
        self.lbNomeTabela.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lbNomeTabela.setAlignment(QtCore.Qt.AlignCenter)
        self.lbNomeTabela.setObjectName("lbNomeTabela")
        self.horizontalLayout_4.addWidget(self.lbNomeTabela)
        self.gridLayout_4.addWidget(self.frNomeTabela, 1, 1, 1, 1)
        self.frCmbFilter = QtWidgets.QFrame(self.frListButtons)
        self.frCmbFilter.setMinimumSize(QtCore.QSize(140, 0))
        self.frCmbFilter.setMaximumSize(QtCore.QSize(170, 60))
        self.frCmbFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCmbFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCmbFilter.setObjectName("frCmbFilter")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frCmbFilter)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox = QtWidgets.QComboBox(self.frCmbFilter)
        self.comboBox.setMaximumSize(QtCore.QSize(140, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_18.addWidget(self.comboBox)
        self.gridLayout_4.addWidget(self.frCmbFilter, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.leSearchCliente = QtWidgets.QLineEdit(self.frListButtons)
        self.leSearchCliente.setObjectName("leSearchCliente")
        self.gridLayout_4.addWidget(self.leSearchCliente, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frListButtons, 1, 0, 1, 2)
        self.frInfoCliente = QtWidgets.QFrame(self.tbInfosCliente)
        self.frInfoCliente.setMinimumSize(QtCore.QSize(300, 0))
        self.frInfoCliente.setStyleSheet("")
        self.frInfoCliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoCliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCliente.setObjectName("frInfoCliente")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frInfoCliente)
        self.verticalLayout_4.setContentsMargins(8, 8, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frInfoTitulo = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoTitulo.setMinimumSize(QtCore.QSize(0, 60))
        self.frInfoTitulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoTitulo.setObjectName("frInfoTitulo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frInfoTitulo)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbInfoTitulo = QtWidgets.QLabel(self.frInfoTitulo)
        self.lbInfoTitulo.setObjectName("lbInfoTitulo")
        self.verticalLayout_7.addWidget(self.lbInfoTitulo)
        self.lbInfoDescricao = QtWidgets.QLabel(self.frInfoTitulo)
        self.lbInfoDescricao.setWordWrap(True)
        self.lbInfoDescricao.setObjectName("lbInfoDescricao")
        self.verticalLayout_7.addWidget(self.lbInfoDescricao)
        self.verticalLayout_4.addWidget(self.frInfoTitulo)
        self.frInformacoes = QtWidgets.QFrame(self.frInfoCliente)
        self.frInformacoes.setMinimumSize(QtCore.QSize(0, 36))
        self.frInformacoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInformacoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInformacoes.setObjectName("frInformacoes")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frInformacoes)
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_21.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_21.setSpacing(16)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbInformacoes = QtWidgets.QLabel(self.frInformacoes)
        self.lbInformacoes.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInformacoes.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(25)
        self.lbInformacoes.setFont(font)
        self.lbInformacoes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInformacoes.setObjectName("lbInformacoes")
        self.horizontalLayout_21.addWidget(self.lbInformacoes)
        self.cbInfoAtivo = QtWidgets.QCheckBox(self.frInformacoes)
        self.cbInfoAtivo.setMinimumSize(QtCore.QSize(0, 30))
        self.cbInfoAtivo.setTristate(False)
        self.cbInfoAtivo.setObjectName("cbInfoAtivo")
        self.horizontalLayout_21.addWidget(self.cbInfoAtivo)
        self.verticalLayout_4.addWidget(self.frInformacoes)
        self.frInfoNome = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoNome.setMinimumSize(QtCore.QSize(0, 36))
        self.frInfoNome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoNome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoNome.setObjectName("frInfoNome")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frInfoNome)
        self.horizontalLayout_22.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_22.setSpacing(16)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbInfoNome = QtWidgets.QLabel(self.frInfoNome)
        self.lbInfoNome.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoNome.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoNome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoNome.setObjectName("lbInfoNome")
        self.horizontalLayout_22.addWidget(self.lbInfoNome)
        self.leInfoNome = QtWidgets.QLineEdit(self.frInfoNome)
        self.leInfoNome.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoNome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoNome.setMaxLength(20)
        self.leInfoNome.setObjectName("leInfoNome")
        self.horizontalLayout_22.addWidget(self.leInfoNome)
        self.leInfoSobrenome = QtWidgets.QLineEdit(self.frInfoNome)
        self.leInfoSobrenome.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoSobrenome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoSobrenome.setMaxLength(30)
        self.leInfoSobrenome.setObjectName("leInfoSobrenome")
        self.horizontalLayout_22.addWidget(self.leInfoSobrenome)
        self.verticalLayout_4.addWidget(self.frInfoNome)
        self.frInfoTel = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoTel.setMinimumSize(QtCore.QSize(0, 36))
        self.frInfoTel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoTel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoTel.setObjectName("frInfoTel")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frInfoTel)
        self.horizontalLayout_24.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_24.setSpacing(16)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbInfoTel = QtWidgets.QLabel(self.frInfoTel)
        self.lbInfoTel.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoTel.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoTel.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoTel.setObjectName("lbInfoTel")
        self.horizontalLayout_24.addWidget(self.lbInfoTel)
        self.leInfoTel = QtWidgets.QLineEdit(self.frInfoTel)
        self.leInfoTel.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoTel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoTel.setMaxLength(20)
        self.leInfoTel.setObjectName("leInfoTel")
        self.horizontalLayout_24.addWidget(self.leInfoTel)
        self.verticalLayout_4.addWidget(self.frInfoTel)
        self.frInfoEmail = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoEmail.setMinimumSize(QtCore.QSize(0, 36))
        self.frInfoEmail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoEmail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoEmail.setObjectName("frInfoEmail")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frInfoEmail)
        self.horizontalLayout_25.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_25.setSpacing(16)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lbInfoEmail = QtWidgets.QLabel(self.frInfoEmail)
        self.lbInfoEmail.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoEmail.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoEmail.setObjectName("lbInfoEmail")
        self.horizontalLayout_25.addWidget(self.lbInfoEmail)
        self.leInfoEmail = QtWidgets.QLineEdit(self.frInfoEmail)
        self.leInfoEmail.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoEmail.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoEmail.setMaxLength(40)
        self.leInfoEmail.setObjectName("leInfoEmail")
        self.horizontalLayout_25.addWidget(self.leInfoEmail)
        self.verticalLayout_4.addWidget(self.frInfoEmail)
        self.frInfoCpf = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoCpf.setMinimumSize(QtCore.QSize(0, 36))
        self.frInfoCpf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoCpf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCpf.setObjectName("frInfoCpf")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frInfoCpf)
        self.horizontalLayout_26.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_26.setSpacing(16)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lbInfoCpf = QtWidgets.QLabel(self.frInfoCpf)
        self.lbInfoCpf.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoCpf.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoCpf.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoCpf.setObjectName("lbInfoCpf")
        self.horizontalLayout_26.addWidget(self.lbInfoCpf)
        self.leInfoCpf = QtWidgets.QLineEdit(self.frInfoCpf)
        self.leInfoCpf.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoCpf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoCpf.setMaxLength(20)
        self.leInfoCpf.setObjectName("leInfoCpf")
        self.horizontalLayout_26.addWidget(self.leInfoCpf)
        self.verticalLayout_4.addWidget(self.frInfoCpf)
        self.frInfoEndereco = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoEndereco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoEndereco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoEndereco.setObjectName("frInfoEndereco")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frInfoEndereco)
        self.horizontalLayout_27.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_27.setSpacing(16)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.lbInfoEndereco = QtWidgets.QLabel(self.frInfoEndereco)
        self.lbInfoEndereco.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoEndereco.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoEndereco.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoEndereco.setObjectName("lbInfoEndereco")
        self.horizontalLayout_27.addWidget(self.lbInfoEndereco)
        self.leInfoEndereco = QtWidgets.QLineEdit(self.frInfoEndereco)
        self.leInfoEndereco.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoEndereco.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoEndereco.setMaxLength(50)
        self.leInfoEndereco.setObjectName("leInfoEndereco")
        self.horizontalLayout_27.addWidget(self.leInfoEndereco)
        self.verticalLayout_4.addWidget(self.frInfoEndereco)
        self.frInfoComplemento = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoComplemento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoComplemento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoComplemento.setObjectName("frInfoComplemento")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frInfoComplemento)
        self.horizontalLayout_28.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_28.setSpacing(16)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lbInfoComplemento = QtWidgets.QLabel(self.frInfoComplemento)
        self.lbInfoComplemento.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoComplemento.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoComplemento.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoComplemento.setObjectName("lbInfoComplemento")
        self.horizontalLayout_28.addWidget(self.lbInfoComplemento)
        self.leInfoComplemento = QtWidgets.QLineEdit(self.frInfoComplemento)
        self.leInfoComplemento.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoComplemento.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoComplemento.setMaxLength(30)
        self.leInfoComplemento.setObjectName("leInfoComplemento")
        self.horizontalLayout_28.addWidget(self.leInfoComplemento)
        self.verticalLayout_4.addWidget(self.frInfoComplemento)
        self.frInfoCep = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoCep.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoCep.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCep.setObjectName("frInfoCep")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frInfoCep)
        self.horizontalLayout_31.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_31.setSpacing(16)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.lbInfoCep = QtWidgets.QLabel(self.frInfoCep)
        self.lbInfoCep.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoCep.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoCep.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoCep.setObjectName("lbInfoCep")
        self.horizontalLayout_31.addWidget(self.lbInfoCep)
        self.leInfoCep = QtWidgets.QLineEdit(self.frInfoCep)
        self.leInfoCep.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoCep.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoCep.setMaxLength(15)
        self.leInfoCep.setObjectName("leInfoCep")
        self.horizontalLayout_31.addWidget(self.leInfoCep)
        self.verticalLayout_4.addWidget(self.frInfoCep)
        self.frInfoBairro = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoBairro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoBairro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoBairro.setObjectName("frInfoBairro")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frInfoBairro)
        self.horizontalLayout_29.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_29.setSpacing(16)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lbInfoBairro = QtWidgets.QLabel(self.frInfoBairro)
        self.lbInfoBairro.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoBairro.setMaximumSize(QtCore.QSize(130, 30))
        self.lbInfoBairro.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoBairro.setObjectName("lbInfoBairro")
        self.horizontalLayout_29.addWidget(self.lbInfoBairro)
        self.leInfoBairro = QtWidgets.QLineEdit(self.frInfoBairro)
        self.leInfoBairro.setMinimumSize(QtCore.QSize(0, 30))
        self.leInfoBairro.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leInfoBairro.setMaxLength(30)
        self.leInfoBairro.setObjectName("leInfoBairro")
        self.horizontalLayout_29.addWidget(self.leInfoBairro)
        self.verticalLayout_4.addWidget(self.frInfoBairro)
        self.frInfoMeioPag = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoMeioPag.setMaximumSize(QtCore.QSize(359, 16777215))
        self.frInfoMeioPag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoMeioPag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoMeioPag.setObjectName("frInfoMeioPag")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frInfoMeioPag)
        self.horizontalLayout_30.setContentsMargins(2, 2, 16, 2)
        self.horizontalLayout_30.setSpacing(16)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lbInfoMeioPag = QtWidgets.QLabel(self.frInfoMeioPag)
        self.lbInfoMeioPag.setMinimumSize(QtCore.QSize(130, 30))
        self.lbInfoMeioPag.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(25)
        self.lbInfoMeioPag.setFont(font)
        self.lbInfoMeioPag.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoMeioPag.setObjectName("lbInfoMeioPag")
        self.horizontalLayout_30.addWidget(self.lbInfoMeioPag)
        self.cbxInfoMeioPag = QtWidgets.QComboBox(self.frInfoMeioPag)
        self.cbxInfoMeioPag.setMinimumSize(QtCore.QSize(0, 30))
        self.cbxInfoMeioPag.setMaximumSize(QtCore.QSize(200, 30))
        self.cbxInfoMeioPag.setObjectName("cbxInfoMeioPag")
        self.horizontalLayout_30.addWidget(self.cbxInfoMeioPag)
        self.verticalLayout_4.addWidget(self.frInfoMeioPag)
        self.frInfoConfirmar = QtWidgets.QFrame(self.frInfoCliente)
        self.frInfoConfirmar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoConfirmar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoConfirmar.setObjectName("frInfoConfirmar")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frInfoConfirmar)
        self.horizontalLayout_32.setContentsMargins(-1, -1, 16, -1)
        self.horizontalLayout_32.setSpacing(16)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pbEnviarEmail = QtWidgets.QPushButton(self.frInfoConfirmar)
        self.pbEnviarEmail.setMinimumSize(QtCore.QSize(0, 30))
        self.pbEnviarEmail.setObjectName("pbEnviarEmail")
        self.horizontalLayout_32.addWidget(self.pbEnviarEmail)
        spacerItem2 = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem2)
        self.pbCancelarEdicao = QtWidgets.QPushButton(self.frInfoConfirmar)
        self.pbCancelarEdicao.setMinimumSize(QtCore.QSize(0, 30))
        self.pbCancelarEdicao.setObjectName("pbCancelarEdicao")
        self.horizontalLayout_32.addWidget(self.pbCancelarEdicao)
        self.pbConfirmarAtualizacao = QtWidgets.QPushButton(self.frInfoConfirmar)
        self.pbConfirmarAtualizacao.setMinimumSize(QtCore.QSize(0, 30))
        self.pbConfirmarAtualizacao.setObjectName("pbConfirmarAtualizacao")
        self.horizontalLayout_32.addWidget(self.pbConfirmarAtualizacao)
        self.verticalLayout_4.addWidget(self.frInfoConfirmar)
        self.gridLayout_3.addWidget(self.frInfoCliente, 1, 2, 2, 1)
        self.frTopTabMenu = QtWidgets.QFrame(self.tbInfosCliente)
        self.frTopTabMenu.setMinimumSize(QtCore.QSize(0, 80))
        self.frTopTabMenu.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frTopTabMenu.setStyleSheet("")
        self.frTopTabMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTopTabMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTopTabMenu.setObjectName("frTopTabMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frTopTabMenu)
        self.horizontalLayout_2.setContentsMargins(9, 0, 150, 9)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frClientesTotal = QtWidgets.QFrame(self.frTopTabMenu)
        self.frClientesTotal.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frClientesTotal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frClientesTotal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frClientesTotal.setObjectName("frClientesTotal")
        self.lbTituloTotal = QtWidgets.QLabel(self.frClientesTotal)
        self.lbTituloTotal.setGeometry(QtCore.QRect(10, 0, 121, 24))
        self.lbTituloTotal.setMinimumSize(QtCore.QSize(0, 24))
        self.lbTituloTotal.setMaximumSize(QtCore.QSize(654654, 24))
        self.lbTituloTotal.setStyleSheet("")
        self.lbTituloTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbTituloTotal.setObjectName("lbTituloTotal")
        self.lbValorTotal = QtWidgets.QLabel(self.frClientesTotal)
        self.lbValorTotal.setGeometry(QtCore.QRect(60, 30, 81, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbValorTotal.sizePolicy().hasHeightForWidth())
        self.lbValorTotal.setSizePolicy(sizePolicy)
        self.lbValorTotal.setMinimumSize(QtCore.QSize(0, 40))
        self.lbValorTotal.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lbValorTotal.setObjectName("lbValorTotal")
        self.lbEstTotal = QtWidgets.QLabel(self.frClientesTotal)
        self.lbEstTotal.setGeometry(QtCore.QRect(30, 50, 41, 16))
        self.lbEstTotal.setMinimumSize(QtCore.QSize(0, 16))
        self.lbEstTotal.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbEstTotal.setObjectName("lbEstTotal")
        self.horizontalLayout_2.addWidget(self.frClientesTotal)
        self.frClientesMensal = QtWidgets.QFrame(self.frTopTabMenu)
        self.frClientesMensal.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frClientesMensal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frClientesMensal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frClientesMensal.setObjectName("frClientesMensal")
        self.lbTituloMensal = QtWidgets.QLabel(self.frClientesMensal)
        self.lbTituloMensal.setGeometry(QtCore.QRect(10, 0, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTituloMensal.sizePolicy().hasHeightForWidth())
        self.lbTituloMensal.setSizePolicy(sizePolicy)
        self.lbTituloMensal.setMaximumSize(QtCore.QSize(65466, 94654))
        self.lbTituloMensal.setStyleSheet("")
        self.lbTituloMensal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbTituloMensal.setWordWrap(True)
        self.lbTituloMensal.setObjectName("lbTituloMensal")
        self.lbValorMensal = QtWidgets.QLabel(self.frClientesMensal)
        self.lbValorMensal.setGeometry(QtCore.QRect(80, 30, 64, 40))
        self.lbValorMensal.setMinimumSize(QtCore.QSize(0, 40))
        self.lbValorMensal.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lbValorMensal.setObjectName("lbValorMensal")
        self.lbEstMensal = QtWidgets.QLabel(self.frClientesMensal)
        self.lbEstMensal.setGeometry(QtCore.QRect(50, 50, 41, 17))
        self.lbEstMensal.setObjectName("lbEstMensal")
        self.horizontalLayout_2.addWidget(self.frClientesMensal)
        self.frClientesAnuais = QtWidgets.QFrame(self.frTopTabMenu)
        self.frClientesAnuais.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frClientesAnuais.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frClientesAnuais.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frClientesAnuais.setObjectName("frClientesAnuais")
        self.lbTituloAnual = QtWidgets.QLabel(self.frClientesAnuais)
        self.lbTituloAnual.setGeometry(QtCore.QRect(10, 0, 121, 41))
        self.lbTituloAnual.setMaximumSize(QtCore.QSize(6544, 6546))
        self.lbTituloAnual.setStyleSheet("")
        self.lbTituloAnual.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbTituloAnual.setWordWrap(True)
        self.lbTituloAnual.setObjectName("lbTituloAnual")
        self.lbValorAnual = QtWidgets.QLabel(self.frClientesAnuais)
        self.lbValorAnual.setGeometry(QtCore.QRect(80, 30, 64, 40))
        self.lbValorAnual.setObjectName("lbValorAnual")
        self.lbEstAnual = QtWidgets.QLabel(self.frClientesAnuais)
        self.lbEstAnual.setGeometry(QtCore.QRect(40, 50, 64, 17))
        self.lbEstAnual.setObjectName("lbEstAnual")
        self.horizontalLayout_2.addWidget(self.frClientesAnuais)
        self.frClientes = QtWidgets.QFrame(self.frTopTabMenu)
        self.frClientes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frClientes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frClientes.setObjectName("frClientes")
        self.leCard4 = QtWidgets.QLabel(self.frClientes)
        self.leCard4.setGeometry(QtCore.QRect(20, 0, 170, 71))
        self.leCard4.setMaximumSize(QtCore.QSize(300, 110))
        self.leCard4.setStyleSheet("")
        self.leCard4.setAlignment(QtCore.Qt.AlignCenter)
        self.leCard4.setObjectName("leCard4")
        self.horizontalLayout_2.addWidget(self.frClientes)
        self.gridLayout_3.addWidget(self.frTopTabMenu, 0, 0, 1, 3)
        self.tabsCliente.addTab(self.tbInfosCliente, "")
        self.tbCadastraCliente = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCadastraCliente.sizePolicy().hasHeightForWidth())
        self.tbCadastraCliente.setSizePolicy(sizePolicy)
        self.tbCadastraCliente.setStyleSheet("")
        self.tbCadastraCliente.setObjectName("tbCadastraCliente")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tbCadastraCliente)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frCabecalho = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frCabecalho.setMinimumSize(QtCore.QSize(600, 100))
        self.frCabecalho.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frCabecalho)
        self.verticalLayout_3.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbTitulo = QtWidgets.QLabel(self.frCabecalho)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(37)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbTitulo.setObjectName("lbTitulo")
        self.verticalLayout_3.addWidget(self.lbTitulo)
        self.lbCorpo = QtWidgets.QLabel(self.frCabecalho)
        self.lbCorpo.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbCorpo.setObjectName("lbCorpo")
        self.verticalLayout_3.addWidget(self.lbCorpo)
        self.gridLayout_2.addWidget(self.frCabecalho, 0, 0, 1, 1)
        self.frNomeSobrenome = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frNomeSobrenome.setMinimumSize(QtCore.QSize(600, 60))
        self.frNomeSobrenome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frNomeSobrenome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frNomeSobrenome.setObjectName("frNomeSobrenome")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frNomeSobrenome)
        self.horizontalLayout_5.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frNome = QtWidgets.QFrame(self.frNomeSobrenome)
        self.frNome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frNome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frNome.setObjectName("frNome")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frNome)
        self.horizontalLayout_9.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbNome = QtWidgets.QLabel(self.frNome)
        self.lbNome.setMinimumSize(QtCore.QSize(130, 0))
        self.lbNome.setMaximumSize(QtCore.QSize(150, 30))
        self.lbNome.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbNome.setTextFormat(QtCore.Qt.RichText)
        self.lbNome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbNome.setObjectName("lbNome")
        self.horizontalLayout_9.addWidget(self.lbNome)
        self.leNome = QtWidgets.QLineEdit(self.frNome)
        self.leNome.setMinimumSize(QtCore.QSize(0, 30))
        self.leNome.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leNome.setStyleSheet("")
        self.leNome.setInputMask("")
        self.leNome.setText("")
        self.leNome.setMaxLength(20)
        self.leNome.setObjectName("leNome")
        self.horizontalLayout_9.addWidget(self.leNome)
        self.leNome.raise_()
        self.lbNome.raise_()
        self.horizontalLayout_5.addWidget(self.frNome)
        self.frSobrenome = QtWidgets.QFrame(self.frNomeSobrenome)
        self.frSobrenome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frSobrenome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSobrenome.setObjectName("frSobrenome")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frSobrenome)
        self.horizontalLayout_10.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbSobrenome = QtWidgets.QLabel(self.frSobrenome)
        self.lbSobrenome.setMinimumSize(QtCore.QSize(130, 30))
        self.lbSobrenome.setMaximumSize(QtCore.QSize(150, 30))
        self.lbSobrenome.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbSobrenome.setTextFormat(QtCore.Qt.RichText)
        self.lbSobrenome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSobrenome.setObjectName("lbSobrenome")
        self.horizontalLayout_10.addWidget(self.lbSobrenome)
        self.leSobrenome = QtWidgets.QLineEdit(self.frSobrenome)
        self.leSobrenome.setMinimumSize(QtCore.QSize(0, 30))
        self.leSobrenome.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leSobrenome.setStyleSheet("")
        self.leSobrenome.setMaxLength(30)
        self.leSobrenome.setObjectName("leSobrenome")
        self.horizontalLayout_10.addWidget(self.leSobrenome)
        self.leSobrenome.raise_()
        self.lbSobrenome.raise_()
        self.horizontalLayout_5.addWidget(self.frSobrenome)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_2.addWidget(self.frNomeSobrenome, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, -1, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbCadastrar = QtWidgets.QPushButton(self.frame)
        self.pbCadastrar.setMinimumSize(QtCore.QSize(80, 50))
        self.pbCadastrar.setMaximumSize(QtCore.QSize(200, 50))
        self.pbCadastrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbCadastrar.setStyleSheet("")
        self.pbCadastrar.setObjectName("pbCadastrar")
        self.horizontalLayout.addWidget(self.pbCadastrar)
        self.gridLayout_2.addWidget(self.frame, 5, 0, 1, 1)
        self.frEmailTel = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frEmailTel.setMinimumSize(QtCore.QSize(600, 60))
        self.frEmailTel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frEmailTel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frEmailTel.setObjectName("frEmailTel")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frEmailTel)
        self.horizontalLayout_6.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_6.setSpacing(50)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frTel = QtWidgets.QFrame(self.frEmailTel)
        self.frTel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTel.setObjectName("frTel")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frTel)
        self.horizontalLayout_11.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbTel = QtWidgets.QLabel(self.frTel)
        self.lbTel.setMinimumSize(QtCore.QSize(130, 0))
        self.lbTel.setMaximumSize(QtCore.QSize(150, 30))
        self.lbTel.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbTel.setTextFormat(QtCore.Qt.RichText)
        self.lbTel.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTel.setObjectName("lbTel")
        self.horizontalLayout_11.addWidget(self.lbTel)
        self.leTel = QtWidgets.QLineEdit(self.frTel)
        self.leTel.setMinimumSize(QtCore.QSize(0, 30))
        self.leTel.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leTel.setStyleSheet("")
        self.leTel.setMaxLength(19)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_11.addWidget(self.leTel)
        self.horizontalLayout_6.addWidget(self.frTel)
        self.frEmail = QtWidgets.QFrame(self.frEmailTel)
        self.frEmail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frEmail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frEmail.setObjectName("frEmail")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frEmail)
        self.horizontalLayout_12.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbEmail = QtWidgets.QLabel(self.frEmail)
        self.lbEmail.setMinimumSize(QtCore.QSize(130, 0))
        self.lbEmail.setMaximumSize(QtCore.QSize(150, 30))
        self.lbEmail.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbEmail.setTextFormat(QtCore.Qt.RichText)
        self.lbEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.lbEmail.setObjectName("lbEmail")
        self.horizontalLayout_12.addWidget(self.lbEmail)
        self.leEmail = QtWidgets.QLineEdit(self.frEmail)
        self.leEmail.setMinimumSize(QtCore.QSize(0, 30))
        self.leEmail.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leEmail.setStyleSheet("")
        self.leEmail.setMaxLength(40)
        self.leEmail.setObjectName("leEmail")
        self.horizontalLayout_12.addWidget(self.leEmail)
        self.horizontalLayout_6.addWidget(self.frEmail)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout_2.addWidget(self.frEmailTel, 2, 0, 1, 1)
        self.frCepEnd = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frCepEnd.setMinimumSize(QtCore.QSize(600, 60))
        self.frCepEnd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCepEnd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCepEnd.setObjectName("frCepEnd")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frCepEnd)
        self.horizontalLayout_7.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_7.setSpacing(50)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frCep = QtWidgets.QFrame(self.frCepEnd)
        self.frCep.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCep.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCep.setObjectName("frCep")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frCep)
        self.horizontalLayout_13.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbCep = QtWidgets.QLabel(self.frCep)
        self.lbCep.setMinimumSize(QtCore.QSize(130, 0))
        self.lbCep.setMaximumSize(QtCore.QSize(150, 30))
        self.lbCep.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbCep.setTextFormat(QtCore.Qt.RichText)
        self.lbCep.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCep.setObjectName("lbCep")
        self.horizontalLayout_13.addWidget(self.lbCep)
        self.leCep = QtWidgets.QLineEdit(self.frCep)
        self.leCep.setMinimumSize(QtCore.QSize(0, 30))
        self.leCep.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leCep.setStyleSheet("")
        self.leCep.setMaxLength(15)
        self.leCep.setObjectName("leCep")
        self.horizontalLayout_13.addWidget(self.leCep)
        self.horizontalLayout_7.addWidget(self.frCep)
        self.frEndereco = QtWidgets.QFrame(self.frCepEnd)
        self.frEndereco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frEndereco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frEndereco.setObjectName("frEndereco")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frEndereco)
        self.horizontalLayout_14.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbEnd = QtWidgets.QLabel(self.frEndereco)
        self.lbEnd.setMinimumSize(QtCore.QSize(130, 0))
        self.lbEnd.setMaximumSize(QtCore.QSize(150, 30))
        self.lbEnd.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbEnd.setTextFormat(QtCore.Qt.RichText)
        self.lbEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.lbEnd.setObjectName("lbEnd")
        self.horizontalLayout_14.addWidget(self.lbEnd)
        self.leEnd = QtWidgets.QLineEdit(self.frEndereco)
        self.leEnd.setMinimumSize(QtCore.QSize(0, 30))
        self.leEnd.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leEnd.setStyleSheet("")
        self.leEnd.setMaxLength(50)
        self.leEnd.setObjectName("leEnd")
        self.horizontalLayout_14.addWidget(self.leEnd)
        self.horizontalLayout_7.addWidget(self.frEndereco)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.frCepEnd, 3, 0, 1, 1)
        self.frBairroCompl = QtWidgets.QFrame(self.tbCadastraCliente)
        self.frBairroCompl.setMinimumSize(QtCore.QSize(600, 60))
        self.frBairroCompl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBairroCompl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBairroCompl.setObjectName("frBairroCompl")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frBairroCompl)
        self.horizontalLayout_8.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_8.setSpacing(50)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frBairro = QtWidgets.QFrame(self.frBairroCompl)
        self.frBairro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBairro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBairro.setObjectName("frBairro")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frBairro)
        self.horizontalLayout_15.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lbBairro = QtWidgets.QLabel(self.frBairro)
        self.lbBairro.setMinimumSize(QtCore.QSize(130, 0))
        self.lbBairro.setMaximumSize(QtCore.QSize(150, 30))
        self.lbBairro.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbBairro.setTextFormat(QtCore.Qt.RichText)
        self.lbBairro.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBairro.setObjectName("lbBairro")
        self.horizontalLayout_15.addWidget(self.lbBairro)
        self.leBairro = QtWidgets.QLineEdit(self.frBairro)
        self.leBairro.setMinimumSize(QtCore.QSize(0, 30))
        self.leBairro.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leBairro.setStyleSheet("")
        self.leBairro.setMaxLength(30)
        self.leBairro.setObjectName("leBairro")
        self.horizontalLayout_15.addWidget(self.leBairro)
        self.horizontalLayout_8.addWidget(self.frBairro)
        self.frComplemento = QtWidgets.QFrame(self.frBairroCompl)
        self.frComplemento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frComplemento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frComplemento.setObjectName("frComplemento")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frComplemento)
        self.horizontalLayout_16.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lbCompl = QtWidgets.QLabel(self.frComplemento)
        self.lbCompl.setMinimumSize(QtCore.QSize(130, 0))
        self.lbCompl.setMaximumSize(QtCore.QSize(150, 30))
        self.lbCompl.setStyleSheet("color: rgb(46, 52, 54)")
        self.lbCompl.setTextFormat(QtCore.Qt.RichText)
        self.lbCompl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCompl.setObjectName("lbCompl")
        self.horizontalLayout_16.addWidget(self.lbCompl)
        self.leCompl = QtWidgets.QLineEdit(self.frComplemento)
        self.leCompl.setMinimumSize(QtCore.QSize(0, 30))
        self.leCompl.setMaximumSize(QtCore.QSize(600, 16777215))
        self.leCompl.setStyleSheet("")
        self.leCompl.setMaxLength(30)
        self.leCompl.setObjectName("leCompl")
        self.horizontalLayout_16.addWidget(self.leCompl)
        self.horizontalLayout_8.addWidget(self.frComplemento)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.gridLayout_2.addWidget(self.frBairroCompl, 4, 0, 1, 1)
        self.tabsCliente.addTab(self.tbCadastraCliente, "")
        self.tbGrupoCliente = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbGrupoCliente.sizePolicy().hasHeightForWidth())
        self.tbGrupoCliente.setSizePolicy(sizePolicy)
        self.tbGrupoCliente.setStyleSheet("QComboBox {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #DAA520;\n"
"    color: #000000;\n"
"    padding: 5px;\n"
"    \n"
"    selection-background-color: rgb(83, 162, 193);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"\n"
"#leDescricaoGrupo {\n"
"    padding: 4px;\n"
"}")
        self.tbGrupoCliente.setObjectName("tbGrupoCliente")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tbGrupoCliente)
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frGruposFormados = QtWidgets.QFrame(self.tbGrupoCliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frGruposFormados.sizePolicy().hasHeightForWidth())
        self.frGruposFormados.setSizePolicy(sizePolicy)
        self.frGruposFormados.setStyleSheet("/*background-color: rgb(108, 251, 208);*/")
        self.frGruposFormados.setObjectName("frGruposFormados")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frGruposFormados)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.frGruposFormados)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollGrupos = QtWidgets.QWidget()
        self.scrollGrupos.setGeometry(QtCore.QRect(0, 0, 552, 589))
        self.scrollGrupos.setObjectName("scrollGrupos")
        self.scrollArea.setWidget(self.scrollGrupos)
        self.gridLayout_6.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.frTopCards = QtWidgets.QFrame(self.frGruposFormados)
        self.frTopCards.setMinimumSize(QtCore.QSize(0, 80))
        self.frTopCards.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTopCards.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTopCards.setObjectName("frTopCards")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frTopCards)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(8)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.frame_2 = QtWidgets.QFrame(self.frTopCards)
        self.frame_2.setMinimumSize(QtCore.QSize(410, 80))
        self.frame_2.setMaximumSize(QtCore.QSize(646544, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbCabecalho = QtWidgets.QLabel(self.frame_2)
        self.lbCabecalho.setStyleSheet("#lbCabecalho {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"}")
        self.lbCabecalho.setObjectName("lbCabecalho")
        self.verticalLayout_5.addWidget(self.lbCabecalho)
        self.lbCabecalhoDesc = QtWidgets.QLabel(self.frame_2)
        self.lbCabecalhoDesc.setStyleSheet("#lbCabecalhoDesc {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}")
        self.lbCabecalhoDesc.setObjectName("lbCabecalhoDesc")
        self.verticalLayout_5.addWidget(self.lbCabecalhoDesc)
        self.horizontalLayout_35.addWidget(self.frame_2)
        self.frOrder = QtWidgets.QFrame(self.frTopCards)
        self.frOrder.setMinimumSize(QtCore.QSize(130, 0))
        self.frOrder.setMaximumSize(QtCore.QSize(130, 16777215))
        self.frOrder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOrder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOrder.setObjectName("frOrder")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frOrder)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbOrdenar = QtWidgets.QLabel(self.frOrder)
        self.lbOrdenar.setObjectName("lbOrdenar")
        self.verticalLayout_6.addWidget(self.lbOrdenar)
        self.cbxOrdenar = QtWidgets.QComboBox(self.frOrder)
        self.cbxOrdenar.setStyleSheet("")
        self.cbxOrdenar.setObjectName("cbxOrdenar")
        self.verticalLayout_6.addWidget(self.cbxOrdenar)
        self.horizontalLayout_35.addWidget(self.frOrder)
        self.gridLayout_6.addWidget(self.frTopCards, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frGruposFormados)
        self.frFormarGrupos = QtWidgets.QFrame(self.tbGrupoCliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frFormarGrupos.sizePolicy().hasHeightForWidth())
        self.frFormarGrupos.setSizePolicy(sizePolicy)
        self.frFormarGrupos.setMinimumSize(QtCore.QSize(500, 0))
        self.frFormarGrupos.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frFormarGrupos.setStyleSheet("#frFormarGrupos {\n"
"    background-color: rgb(238, 238, 236)\n"
"}")
        self.frFormarGrupos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frFormarGrupos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFormarGrupos.setObjectName("frFormarGrupos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frFormarGrupos)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frCabecalhoGrupo = QtWidgets.QFrame(self.frFormarGrupos)
        self.frCabecalhoGrupo.setMinimumSize(QtCore.QSize(0, 50))
        self.frCabecalhoGrupo.setStyleSheet("#frCabecalhoGrupo {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"}")
        self.frCabecalhoGrupo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frCabecalhoGrupo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalhoGrupo.setObjectName("frCabecalhoGrupo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frCabecalhoGrupo)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbTituloGrupo = QtWidgets.QLabel(self.frCabecalhoGrupo)
        self.lbTituloGrupo.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbTituloGrupo.setFont(font)
        self.lbTituloGrupo.setStyleSheet("#lbTituloGrupo {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"}")
        self.lbTituloGrupo.setObjectName("lbTituloGrupo")
        self.verticalLayout_2.addWidget(self.lbTituloGrupo)
        self.lbDica = QtWidgets.QLabel(self.frCabecalhoGrupo)
        self.lbDica.setStyleSheet("#lbDica {\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"}")
        self.lbDica.setWordWrap(True)
        self.lbDica.setObjectName("lbDica")
        self.verticalLayout_2.addWidget(self.lbDica)
        self.verticalLayout.addWidget(self.frCabecalhoGrupo)
        self.frTitulo = QtWidgets.QFrame(self.frFormarGrupos)
        self.frTitulo.setMinimumSize(QtCore.QSize(0, 32))
        self.frTitulo.setStyleSheet("#frTitulo {\n"
"    background-color: transparent;\n"
"}")
        self.frTitulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTitulo.setObjectName("frTitulo")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frTitulo)
        self.horizontalLayout_17.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_17.setSpacing(8)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lbTitulo_2 = QtWidgets.QLabel(self.frTitulo)
        self.lbTitulo_2.setMinimumSize(QtCore.QSize(0, 32))
        self.lbTitulo_2.setStyleSheet("")
        self.lbTitulo_2.setObjectName("lbTitulo_2")
        self.horizontalLayout_17.addWidget(self.lbTitulo_2)
        self.leTituloGrupo = QtWidgets.QLineEdit(self.frTitulo)
        self.leTituloGrupo.setStyleSheet("#leTituloGrupo {\n"
"    background-color: transparent;\n"
"}")
        self.leTituloGrupo.setMaxLength(30)
        self.leTituloGrupo.setObjectName("leTituloGrupo")
        self.horizontalLayout_17.addWidget(self.leTituloGrupo)
        self.verticalLayout.addWidget(self.frTitulo)
        self.frDescricao = QtWidgets.QFrame(self.frFormarGrupos)
        self.frDescricao.setMinimumSize(QtCore.QSize(0, 110))
        self.frDescricao.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frDescricao.setStyleSheet("#frDescricao {\n"
"    background-color: transparent;\n"
"}")
        self.frDescricao.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frDescricao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frDescricao.setObjectName("frDescricao")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frDescricao)
        self.horizontalLayout_23.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_23.setSpacing(8)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frInformativo = QtWidgets.QFrame(self.frDescricao)
        self.frInformativo.setMinimumSize(QtCore.QSize(100, 0))
        self.frInformativo.setStyleSheet("#frInformativo {\n"
"background-color: transparent;\n"
"}")
        self.frInformativo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInformativo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInformativo.setObjectName("frInformativo")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frInformativo)
        self.gridLayout_7.setContentsMargins(2, 5, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbDescricao = QtWidgets.QLabel(self.frInformativo)
        self.lbDescricao.setMinimumSize(QtCore.QSize(0, 32))
        self.lbDescricao.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lbDescricao.setStyleSheet("")
        self.lbDescricao.setAlignment(QtCore.Qt.AlignCenter)
        self.lbDescricao.setObjectName("lbDescricao")
        self.gridLayout_7.addWidget(self.lbDescricao, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 1, 0, 1, 1)
        self.horizontalLayout_23.addWidget(self.frInformativo)
        self.leDescricaoGrupo = QtWidgets.QTextEdit(self.frDescricao)
        self.leDescricaoGrupo.setMinimumSize(QtCore.QSize(0, 0))
        self.leDescricaoGrupo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.leDescricaoGrupo.setObjectName("leDescricaoGrupo")
        self.horizontalLayout_23.addWidget(self.leDescricaoGrupo)
        self.verticalLayout.addWidget(self.frDescricao)
        self.frCategorias = QtWidgets.QFrame(self.frFormarGrupos)
        self.frCategorias.setMinimumSize(QtCore.QSize(0, 32))
        self.frCategorias.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frCategorias.setStyleSheet("#frCategorias {\n"
"    background-color: transparent;\n"
"}")
        self.frCategorias.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCategorias.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCategorias.setObjectName("frCategorias")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frCategorias)
        self.horizontalLayout_34.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_34.setSpacing(16)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.lbCategoria = QtWidgets.QLabel(self.frCategorias)
        self.lbCategoria.setStyleSheet("")
        self.lbCategoria.setObjectName("lbCategoria")
        self.horizontalLayout_34.addWidget(self.lbCategoria)
        self.cbxCategoria = QtWidgets.QComboBox(self.frCategorias)
        self.cbxCategoria.setMinimumSize(QtCore.QSize(0, 0))
        self.cbxCategoria.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbxCategoria.setObjectName("cbxCategoria")
        self.horizontalLayout_34.addWidget(self.cbxCategoria)
        self.verticalLayout.addWidget(self.frCategorias)
        self.frAlfabeto = QtWidgets.QFrame(self.frFormarGrupos)
        self.frAlfabeto.setMinimumSize(QtCore.QSize(0, 30))
        self.frAlfabeto.setStyleSheet("#frAlfabeto {\n"
"    background-color: transparent;\n"
"}")
        self.frAlfabeto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAlfabeto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAlfabeto.setObjectName("frAlfabeto")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frAlfabeto)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.hlAlfabeto = QtWidgets.QHBoxLayout()
        self.hlAlfabeto.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hlAlfabeto.setSpacing(2)
        self.hlAlfabeto.setObjectName("hlAlfabeto")
        self.horizontalLayout_37.addLayout(self.hlAlfabeto)
        self.verticalLayout.addWidget(self.frAlfabeto)
        self.frParticipantes = QtWidgets.QFrame(self.frFormarGrupos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frParticipantes.sizePolicy().hasHeightForWidth())
        self.frParticipantes.setSizePolicy(sizePolicy)
        self.frParticipantes.setStyleSheet("#frParticipantes {\n"
"    background-color: transparent;\n"
"    border: 0px;\n"
"    padding: 4px;\n"
"}")
        self.frParticipantes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frParticipantes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frParticipantes.setObjectName("frParticipantes")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frParticipantes)
        self.horizontalLayout_36.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.tblParticipantes = QtWidgets.QTableWidget(self.frParticipantes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblParticipantes.sizePolicy().hasHeightForWidth())
        self.tblParticipantes.setSizePolicy(sizePolicy)
        self.tblParticipantes.setMaximumSize(QtCore.QSize(448, 16777215))
        self.tblParticipantes.setStyleSheet("")
        self.tblParticipantes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblParticipantes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblParticipantes.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblParticipantes.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tblParticipantes.setAlternatingRowColors(True)
        self.tblParticipantes.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tblParticipantes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblParticipantes.setIconSize(QtCore.QSize(0, 24))
        self.tblParticipantes.setShowGrid(False)
        self.tblParticipantes.setWordWrap(True)
        self.tblParticipantes.setObjectName("tblParticipantes")
        self.tblParticipantes.setColumnCount(4)
        self.tblParticipantes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblParticipantes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParticipantes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParticipantes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParticipantes.setHorizontalHeaderItem(3, item)
        self.tblParticipantes.horizontalHeader().setVisible(False)
        self.tblParticipantes.horizontalHeader().setCascadingSectionResizes(True)
        self.tblParticipantes.horizontalHeader().setStretchLastSection(False)
        self.tblParticipantes.verticalHeader().setVisible(False)
        self.horizontalLayout_36.addWidget(self.tblParticipantes)
        self.pbRefresh = QtWidgets.QPushButton(self.frParticipantes)
        self.pbRefresh.setStyleSheet("#pbRefresh {\n"
"    background-color: transparent;\n"
"    border: 0px;\n"
"    background-image: url(:/refresh/refresh.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.pbRefresh.setText("")
        self.pbRefresh.setObjectName("pbRefresh")
        self.horizontalLayout_36.addWidget(self.pbRefresh)
        self.verticalLayout.addWidget(self.frParticipantes)
        self.frBottomParticipantes = QtWidgets.QFrame(self.frFormarGrupos)
        self.frBottomParticipantes.setMinimumSize(QtCore.QSize(0, 32))
        self.frBottomParticipantes.setStyleSheet("#frBottomParticipantes{\n"
"    background-color: transparent;\n"
"}")
        self.frBottomParticipantes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBottomParticipantes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBottomParticipantes.setObjectName("frBottomParticipantes")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frBottomParticipantes)
        self.horizontalLayout_33.setContentsMargins(0, 4, 0, 4)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pbAddGrupo = QtWidgets.QPushButton(self.frBottomParticipantes)
        self.pbAddGrupo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbAddGrupo.setStyleSheet("#pbAddGrupo {\n"
"    color: rgb(85, 87, 83);\n"
"    border: 10px;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"}")
        self.pbAddGrupo.setObjectName("pbAddGrupo")
        self.horizontalLayout_33.addWidget(self.pbAddGrupo)
        self.pbCancelar = QtWidgets.QPushButton(self.frBottomParticipantes)
        self.pbCancelar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbCancelar.setStyleSheet("#pbCancelar {\n"
"    /*color: rgb(85, 87, 83);*/\n"
"    border: 10px;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12pt;\n"
"    font-style: italic;\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    background-color: rgb(239, 41, 41);\n"
"}\n"
"\n"
"#pbCancelar::hover{\n"
"    background-color: rgb(114, 159, 207);\n"
"}")
        self.pbCancelar.setObjectName("pbCancelar")
        self.horizontalLayout_33.addWidget(self.pbCancelar)
        self.verticalLayout.addWidget(self.frBottomParticipantes)
        self.frTitulo.raise_()
        self.frDescricao.raise_()
        self.frCabecalhoGrupo.raise_()
        self.frBottomParticipantes.raise_()
        self.frCategorias.raise_()
        self.frAlfabeto.raise_()
        self.frParticipantes.raise_()
        self.horizontalLayout_3.addWidget(self.frFormarGrupos, 0, QtCore.Qt.AlignHCenter)
        self.tabsCliente.addTab(self.tbGrupoCliente, "")
        self.tbBoletoCliente = QtWidgets.QWidget()
        self.tbBoletoCliente.setObjectName("tbBoletoCliente")
        self.tabsCliente.addTab(self.tbBoletoCliente, "")
        self.gridLayout.addWidget(self.tabsCliente, 0, 0, 1, 1)

        self.retranslateUi(wdgCliente)
        self.tabsCliente.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgCliente)

    def retranslateUi(self, wdgCliente):
        _translate = QtCore.QCoreApplication.translate
        wdgCliente.setWindowTitle(_translate("wdgCliente", "Form"))
        item = self.tblClientes.horizontalHeaderItem(0)
        item.setText(_translate("wdgCliente", "Id"))
        item = self.tblClientes.horizontalHeaderItem(1)
        item.setText(_translate("wdgCliente", "Nome"))
        item = self.tblClientes.horizontalHeaderItem(2)
        item.setText(_translate("wdgCliente", "Sobrenome"))
        item = self.tblClientes.horizontalHeaderItem(3)
        item.setText(_translate("wdgCliente", "Celular"))
        item = self.tblClientes.horizontalHeaderItem(4)
        item.setText(_translate("wdgCliente", "Meio de pagamento"))
        item = self.tblClientes.horizontalHeaderItem(5)
        item.setText(_translate("wdgCliente", "Ativo"))
        self.lbTblGeralTitulo.setText(_translate("wdgCliente", "Clientes cadastrados"))
        self.lbTblGeralDescricao.setText(_translate("wdgCliente", "Lista dos clientes cadastrados no banco de dados"))
        self.pbExportar.setText(_translate("wdgCliente", "Exportar"))
        self.lbNomeTabela.setText(_translate("wdgCliente", "Todos os clientes"))
        self.lbInfoTitulo.setText(_translate("wdgCliente", "Informações pessoais"))
        self.lbInfoDescricao.setText(_translate("wdgCliente", "O duplo clique na tabela de clientes (à esquerda) habilita os campos abaixo para edição das informações pessoais."))
        self.lbInformacoes.setText(_translate("wdgCliente", "Informações"))
        self.cbInfoAtivo.setText(_translate("wdgCliente", "Ativo"))
        self.lbInfoNome.setText(_translate("wdgCliente", "Nome"))
        self.leInfoNome.setPlaceholderText(_translate("wdgCliente", "Nome"))
        self.leInfoSobrenome.setPlaceholderText(_translate("wdgCliente", "Sobrenome"))
        self.lbInfoTel.setText(_translate("wdgCliente", "Telefone"))
        self.leInfoTel.setPlaceholderText(_translate("wdgCliente", "(xx) 9.1234-5678"))
        self.lbInfoEmail.setText(_translate("wdgCliente", "E-mail"))
        self.leInfoEmail.setPlaceholderText(_translate("wdgCliente", "cliente@email.com"))
        self.lbInfoCpf.setText(_translate("wdgCliente", "CPF"))
        self.leInfoCpf.setPlaceholderText(_translate("wdgCliente", "123.456.789-00"))
        self.lbInfoEndereco.setText(_translate("wdgCliente", "Endereço"))
        self.leInfoEndereco.setPlaceholderText(_translate("wdgCliente", "Av. Paulista, 258"))
        self.lbInfoComplemento.setText(_translate("wdgCliente", "Complemento"))
        self.leInfoComplemento.setPlaceholderText(_translate("wdgCliente", "Bloco A, Apto: 504"))
        self.lbInfoCep.setText(_translate("wdgCliente", "CEP"))
        self.leInfoCep.setPlaceholderText(_translate("wdgCliente", "12345-678"))
        self.lbInfoBairro.setText(_translate("wdgCliente", "Bairro"))
        self.leInfoBairro.setPlaceholderText(_translate("wdgCliente", "Centro"))
        self.lbInfoMeioPag.setText(_translate("wdgCliente", "Plano Ativo"))
        self.pbEnviarEmail.setText(_translate("wdgCliente", "Enviar e-mail"))
        self.pbCancelarEdicao.setText(_translate("wdgCliente", "Cancelar"))
        self.pbConfirmarAtualizacao.setText(_translate("wdgCliente", "Atualizar"))
        self.lbTituloTotal.setText(_translate("wdgCliente", "<html><head/><body><p>Total de clientes</p></body></html>"))
        self.lbValorTotal.setText(_translate("wdgCliente", "123"))
        self.lbEstTotal.setText(_translate("wdgCliente", "43%"))
        self.lbTituloMensal.setText(_translate("wdgCliente", "<html><head/><body><p>Clientes novos neste mês</p></body></html>"))
        self.lbValorMensal.setText(_translate("wdgCliente", "10"))
        self.lbEstMensal.setText(_translate("wdgCliente", "32%"))
        self.lbTituloAnual.setText(_translate("wdgCliente", "<html><head/><body><p>Clientes novos neste ano</p></body></html>"))
        self.lbValorAnual.setText(_translate("wdgCliente", "50"))
        self.lbEstAnual.setText(_translate("wdgCliente", "10%"))
        self.leCard4.setText(_translate("wdgCliente", "<html><head/><body><p align=\"center\">Compromissos</p><p align=\"center\">da Semana</p></body></html>"))
        self.tabsCliente.setTabText(self.tabsCliente.indexOf(self.tbInfosCliente), _translate("wdgCliente", "Informações"))
        self.lbTitulo.setText(_translate("wdgCliente", "Cadastro de clientes"))
        self.lbCorpo.setText(_translate("wdgCliente", "Cadastre seus clientes para poder gerenciar seus créditos, débitos e grupos."))
        self.lbNome.setText(_translate("wdgCliente", "Nome:    "))
        self.leNome.setPlaceholderText(_translate("wdgCliente", "Nome"))
        self.lbSobrenome.setText(_translate("wdgCliente", "Sobrenome:    "))
        self.leSobrenome.setPlaceholderText(_translate("wdgCliente", "Sobrenome"))
        self.pbCadastrar.setText(_translate("wdgCliente", "Cadastrar"))
        self.lbTel.setText(_translate("wdgCliente", "Telefone:    "))
        self.leTel.setPlaceholderText(_translate("wdgCliente", "Celular"))
        self.lbEmail.setText(_translate("wdgCliente", "<html><head/><body><p align=\"center\">E-mail:    </p></body></html>"))
        self.leEmail.setPlaceholderText(_translate("wdgCliente", "E - mail"))
        self.lbCep.setText(_translate("wdgCliente", "<html><head/><body><p align=\"center\">CEP:    </p></body></html>"))
        self.leCep.setPlaceholderText(_translate("wdgCliente", "CEP"))
        self.lbEnd.setText(_translate("wdgCliente", "<html><head/><body><p align=\"center\">Endereço:     </p></body></html>"))
        self.leEnd.setPlaceholderText(_translate("wdgCliente", "Endereco"))
        self.lbBairro.setText(_translate("wdgCliente", "Bairro:    "))
        self.leBairro.setPlaceholderText(_translate("wdgCliente", "Bairro"))
        self.lbCompl.setText(_translate("wdgCliente", "<html><head/><body><p align=\"center\">Complemento:    </p></body></html>"))
        self.leCompl.setPlaceholderText(_translate("wdgCliente", "Complemento"))
        self.tabsCliente.setTabText(self.tabsCliente.indexOf(self.tbCadastraCliente), _translate("wdgCliente", "Cadastro"))
        self.lbCabecalho.setText(_translate("wdgCliente", "Grupos"))
        self.lbCabecalhoDesc.setText(_translate("wdgCliente", "Dica: Ordene para favorecer sua busca"))
        self.lbOrdenar.setText(_translate("wdgCliente", "Ordenar por:"))
        self.lbTituloGrupo.setText(_translate("wdgCliente", "Criar um grupo"))
        self.lbDica.setText(_translate("wdgCliente", "Criar um grupo facilita o seu trabalho de organização"))
        self.lbTitulo_2.setText(_translate("wdgCliente", "Título"))
        self.lbDescricao.setText(_translate("wdgCliente", "Descrição"))
        self.leDescricaoGrupo.setPlaceholderText(_translate("wdgCliente", "Grupo para alinhamento de propostas.                                                            Máx caracteres 700."))
        self.lbCategoria.setText(_translate("wdgCliente", "Categoria"))
        item = self.tblParticipantes.horizontalHeaderItem(0)
        item.setText(_translate("wdgCliente", "Id"))
        item = self.tblParticipantes.horizontalHeaderItem(1)
        item.setText(_translate("wdgCliente", "Incluir"))
        item = self.tblParticipantes.horizontalHeaderItem(2)
        item.setText(_translate("wdgCliente", "Nome"))
        item = self.tblParticipantes.horizontalHeaderItem(3)
        item.setText(_translate("wdgCliente", "Sobrenome"))
        self.pbAddGrupo.setText(_translate("wdgCliente", "Criar grupo"))
        self.pbCancelar.setText(_translate("wdgCliente", "Cancelar"))
        self.tabsCliente.setTabText(self.tabsCliente.indexOf(self.tbGrupoCliente), _translate("wdgCliente", "Grupos"))
        self.tabsCliente.setTabText(self.tabsCliente.indexOf(self.tbBoletoCliente), _translate("wdgCliente", "Boletos"))
import Telas.Resources.dashClienteResources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgCliente = QtWidgets.QWidget()
    ui = Ui_wdgCliente()
    ui.setupUi(wdgCliente)
    wdgCliente.show()
    sys.exit(app.exec_())
