# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgHome(QtWidgets.QWidget):

    # ----------------------------------
    def __init__(self, parent=None):
        super(Ui_wdgHome, self).__init__()
        self.setupUi(self)
    # ----------------------------------

    def setupUi(self, wdgHome):
        wdgHome.setObjectName("wdgHome")
        wdgHome.resize(844, 723)
        self.gridLayout = QtWidgets.QGridLayout(wdgHome)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(wdgHome)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.IGNORAR_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.IGNORAR_2.setFont(font)
        self.IGNORAR_2.setAlignment(QtCore.Qt.AlignCenter)
        self.IGNORAR_2.setObjectName("IGNORAR_2")
        self.verticalLayout.addWidget(self.IGNORAR_2)
        self.IGNORAR_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.IGNORAR_1.setFont(font)
        self.IGNORAR_1.setAlignment(QtCore.Qt.AlignCenter)
        self.IGNORAR_1.setObjectName("IGNORAR_1")
        self.verticalLayout.addWidget(self.IGNORAR_1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(wdgHome)
        QtCore.QMetaObject.connectSlotsByName(wdgHome)

    def retranslateUi(self, wdgHome):
        _translate = QtCore.QCoreApplication.translate
        wdgHome.setWindowTitle(_translate("wdgHome", "Form"))
        self.IGNORAR_2.setText(_translate("wdgHome", "DashBoard"))
        self.IGNORAR_1.setText(_translate("wdgHome", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgHome = QtWidgets.QWidget()
    ui = Ui_wdgHome()
    ui.setupUi(wdgHome)
    wdgHome.show()
    sys.exit(app.exec_())
