# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Email.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 389)
        Form.setMaximumSize(QtCore.QSize(16777215, 450))
        Form.setStyleSheet("#Form {\n"
"    background-color: rgb(48, 140, 198);\n"
"}\n"
"\n"
"#textEdit {\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 2px tranparent;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(211, 215, 207);\n"
"}\n"
"\n"
"#lbRecebeNomeArquivo {\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(174, 2, 2);\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pbEnviar {\n"
"    background-color: rgb(64, 191, 160);\n"
"\n"
"}\n"
"\n"
"#pbEnviar:hover {\n"
"    background-color: rgb(64, 191, 121);\n"
"}\n"
"\n"
"#pbAnexar:hover {\n"
"    background-color: rgb(173, 127, 168);\n"
"}\n"
"")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leId = QtWidgets.QLineEdit(Form)
        self.leId.setInputMask("")
        self.leId.setText("")
        self.leId.setObjectName("leId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leId)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leNome = QtWidgets.QLineEdit(Form)
        self.leNome.setInputMask("")
        self.leNome.setText("")
        self.leNome.setObjectName("leNome")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leNome)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leEmail = QtWidgets.QLineEdit(Form)
        self.leEmail.setText("")
        self.leEmail.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leEmail.setObjectName("leEmail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leEmail)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leTitulo = QtWidgets.QLineEdit(Form)
        self.leTitulo.setText("")
        self.leTitulo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leTitulo.setObjectName("leTitulo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leTitulo)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.textEdit)
        self.lbRecebeNomeArquivo = QtWidgets.QLabel(Form)
        self.lbRecebeNomeArquivo.setMinimumSize(QtCore.QSize(0, 60))
        self.lbRecebeNomeArquivo.setStyleSheet("#lbRecebeNomeArquivo {\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"}")
        self.lbRecebeNomeArquivo.setText("")
        self.lbRecebeNomeArquivo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbRecebeNomeArquivo.setObjectName("lbRecebeNomeArquivo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.lbRecebeNomeArquivo)
        self.pbAnexar = QtWidgets.QPushButton(Form)
        self.pbAnexar.setMinimumSize(QtCore.QSize(70, 0))
        self.pbAnexar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbAnexar.setObjectName("pbAnexar")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pbAnexar)
        self.pbEnviar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEnviar.sizePolicy().hasHeightForWidth())
        self.pbEnviar.setSizePolicy(sizePolicy)
        self.pbEnviar.setMinimumSize(QtCore.QSize(70, 0))
        self.pbEnviar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbEnviar.setObjectName("pbEnviar")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pbEnviar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Id"))
        self.leId.setPlaceholderText(_translate("Form", "Id"))
        self.label.setText(_translate("Form", "Nome"))
        self.leNome.setPlaceholderText(_translate("Form", "Nome Completo"))
        self.label_2.setText(_translate("Form", "E-mail"))
        self.leEmail.setPlaceholderText(_translate("Form", "E-mail"))
        self.label_4.setText(_translate("Form", "Titulo"))
        self.leTitulo.setPlaceholderText(_translate("Form", "Título do Email"))
        self.pbAnexar.setText(_translate("Form", "Anexar"))
        self.pbEnviar.setText(_translate("Form", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
