# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginCopia.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwLogin(object):
    def setupUi(self, mwLogin):
        mwLogin.setObjectName("mwLogin")
        mwLogin.setWindowModality(QtCore.Qt.NonModal)
        mwLogin.resize(1000, 700)
        mwLogin.setMinimumSize(QtCore.QSize(1000, 700))
        mwLogin.setStyleSheet("QWidget {\n"
"    background-color: #80CCE1; /*Azul externo - mais claro*/\n"
"}\n"
"\n"
"/*------------------------------------------------------------------------------*/\n"
"\n"
"QLabel {\n"
"    font: bold;\n"
"    border-radius: 10px;\n"
"    border: 2px solid  #ffffff;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #DAA520;\n"
"}\n"
"\n"
"/*------------------------------------------------------------------------------*/\n"
"\n"
"QFrame {\n"
"    background-color: #0E90AD; /*Azul Interno-mais escuro*/\n"
"    border-radius: 50%;\n"
"}\n"
"\n"
"#frBordaIretaveisLogin, #frBordaTextuaisLogin  {\n"
"    background-color: #DFD880;\n"
"}\n"
"\n"
"/*------------------------------------------------------------------------------*/\n"
"\n"
"QLineEdit {\n"
"border-radius: 10px;\n"
"color: rgb(136, 138, 133);\n"
"border-bottom-color: rgb(136, 138, 133);\n"
"background-color: #fafafa;\n"
"}")
        mwLogin.setIconSize(QtCore.QSize(25, 25))
        mwLogin.setAnimated(True)
        mwLogin.setDocumentMode(False)
        mwLogin.setTabShape(QtWidgets.QTabWidget.Rounded)
        mwLogin.setDockNestingEnabled(False)
        mwLogin.setUnifiedTitleAndToolBarOnMac(False)
        self.wdgLgin = QtWidgets.QWidget(mwLogin)
        self.wdgLgin.setObjectName("wdgLgin")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgLgin)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stkLogin = QtWidgets.QStackedWidget(self.wdgLgin)
        self.stkLogin.setMinimumSize(QtCore.QSize(100, 0))
        self.stkLogin.setStyleSheet("")
        self.stkLogin.setObjectName("stkLogin")
        self.pgLogin = QtWidgets.QWidget()
        self.pgLogin.setObjectName("pgLogin")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pgLogin)
        self.gridLayout_8.setContentsMargins(0, 9, 0, 9)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        self.frBordaTextuaisLogin = QtWidgets.QFrame(self.pgLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frBordaTextuaisLogin.sizePolicy().hasHeightForWidth())
        self.frBordaTextuaisLogin.setSizePolicy(sizePolicy)
        self.frBordaTextuaisLogin.setMinimumSize(QtCore.QSize(500, 640))
        self.frBordaTextuaisLogin.setMaximumSize(QtCore.QSize(1000, 720))
        self.frBordaTextuaisLogin.setStyleSheet("")
        self.frBordaTextuaisLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBordaTextuaisLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBordaTextuaisLogin.setObjectName("frBordaTextuaisLogin")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frBordaTextuaisLogin)
        self.gridLayout_7.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frTextuaisLogin = QtWidgets.QFrame(self.frBordaTextuaisLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frTextuaisLogin.sizePolicy().hasHeightForWidth())
        self.frTextuaisLogin.setSizePolicy(sizePolicy)
        self.frTextuaisLogin.setMinimumSize(QtCore.QSize(472, 650))
        self.frTextuaisLogin.setMaximumSize(QtCore.QSize(950, 650))
        self.frTextuaisLogin.setStyleSheet("")
        self.frTextuaisLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTextuaisLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTextuaisLogin.setObjectName("frTextuaisLogin")
        self.frame = QtWidgets.QFrame(self.frTextuaisLogin)
        self.frame.setGeometry(QtCore.QRect(80, 170, 301, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7.addWidget(self.frTextuaisLogin, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.frBordaTextuaisLogin, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 4, 1, 1)
        self.frBordaIretaveisLogin = QtWidgets.QFrame(self.pgLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frBordaIretaveisLogin.sizePolicy().hasHeightForWidth())
        self.frBordaIretaveisLogin.setSizePolicy(sizePolicy)
        self.frBordaIretaveisLogin.setMinimumSize(QtCore.QSize(352, 640))
        self.frBordaIretaveisLogin.setMaximumSize(QtCore.QSize(500, 720))
        self.frBordaIretaveisLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frBordaIretaveisLogin.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frBordaIretaveisLogin.setStyleSheet("")
        self.frBordaIretaveisLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBordaIretaveisLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBordaIretaveisLogin.setObjectName("frBordaIretaveisLogin")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frBordaIretaveisLogin)
        self.gridLayout_2.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frPrincipalIteraveis = QtWidgets.QFrame(self.frBordaIretaveisLogin)
        self.frPrincipalIteraveis.setMinimumSize(QtCore.QSize(334, 100))
        self.frPrincipalIteraveis.setMaximumSize(QtCore.QSize(450, 550))
        self.frPrincipalIteraveis.setStyleSheet("")
        self.frPrincipalIteraveis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frPrincipalIteraveis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frPrincipalIteraveis.setObjectName("frPrincipalIteraveis")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frPrincipalIteraveis)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(10, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 0, 1, 1)
        self.frSnackBarLogin = QtWidgets.QFrame(self.frPrincipalIteraveis)
        self.frSnackBarLogin.setMinimumSize(QtCore.QSize(300, 74))
        self.frSnackBarLogin.setStyleSheet("background-color: none;")
        self.frSnackBarLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frSnackBarLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSnackBarLogin.setObjectName("frSnackBarLogin")
        self.lbSnackBarLogin = QtWidgets.QLabel(self.frSnackBarLogin)
        self.lbSnackBarLogin.setGeometry(QtCore.QRect(10, 0, 282, 51))
        self.lbSnackBarLogin.setMinimumSize(QtCore.QSize(282, 51))
        self.lbSnackBarLogin.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setFamily("Dimnah")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbSnackBarLogin.setFont(font)
        self.lbSnackBarLogin.setStyleSheet("QLabel {\n"
"    background-color: #DFD880;\n"
"    border: none;\n"
"    border-top-left-radius: 1px;\n"
"    border-top-right-radius: 1px;\n"
"    font:  14pt \"Dimnah\";\n"
"}\n"
"")
        self.lbSnackBarLogin.setText("")
        self.lbSnackBarLogin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbSnackBarLogin.setObjectName("lbSnackBarLogin")
        self.pbFechaSnackBarLogin = QtWidgets.QPushButton(self.frSnackBarLogin)
        self.pbFechaSnackBarLogin.setGeometry(QtCore.QRect(120, 50, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbFechaSnackBarLogin.sizePolicy().hasHeightForWidth())
        self.pbFechaSnackBarLogin.setSizePolicy(sizePolicy)
        self.pbFechaSnackBarLogin.setMinimumSize(QtCore.QSize(50, 25))
        self.pbFechaSnackBarLogin.setMaximumSize(QtCore.QSize(30, 30))
        self.pbFechaSnackBarLogin.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbFechaSnackBarLogin.setFont(font)
        self.pbFechaSnackBarLogin.setStyleSheet("QPushButton {\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    background-color: #FF6961;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcaaa;\n"
"}\n"
"")
        self.pbFechaSnackBarLogin.setObjectName("pbFechaSnackBarLogin")
        self.gridLayout_3.addWidget(self.frSnackBarLogin, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 5, 4, 1, 1)
        self.gIyInputs = QtWidgets.QGridLayout()
        self.gIyInputs.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gIyInputs.setContentsMargins(7, 25, 0, 10)
        self.gIyInputs.setVerticalSpacing(10)
        self.gIyInputs.setObjectName("gIyInputs")
        self.leUsuario = QtWidgets.QLineEdit(self.frPrincipalIteraveis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leUsuario.sizePolicy().hasHeightForWidth())
        self.leUsuario.setSizePolicy(sizePolicy)
        self.leUsuario.setMinimumSize(QtCore.QSize(200, 40))
        self.leUsuario.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.leUsuario.setFont(font)
        self.leUsuario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leUsuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leUsuario.setStyleSheet("")
        self.leUsuario.setInputMethodHints(QtCore.Qt.ImhNone)
        self.leUsuario.setInputMask("")
        self.leUsuario.setText("")
        self.leUsuario.setFrame(True)
        self.leUsuario.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.leUsuario.setObjectName("leUsuario")
        self.gIyInputs.addWidget(self.leUsuario, 0, 0, 1, 1)
        self.leSenha = QtWidgets.QLineEdit(self.frPrincipalIteraveis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSenha.sizePolicy().hasHeightForWidth())
        self.leSenha.setSizePolicy(sizePolicy)
        self.leSenha.setMinimumSize(QtCore.QSize(200, 40))
        self.leSenha.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.leSenha.setFont(font)
        self.leSenha.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leSenha.setStyleSheet("")
        self.leSenha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.leSenha.setInputMask("")
        self.leSenha.setText("")
        self.leSenha.setFrame(True)
        self.leSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leSenha.setAlignment(QtCore.Qt.AlignCenter)
        self.leSenha.setObjectName("leSenha")
        self.gIyInputs.addWidget(self.leSenha, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gIyInputs, 6, 0, 1, 5)
        self.glytBotoes = QtWidgets.QGridLayout()
        self.glytBotoes.setContentsMargins(0, 22, 0, 40)
        self.glytBotoes.setHorizontalSpacing(6)
        self.glytBotoes.setVerticalSpacing(10)
        self.glytBotoes.setObjectName("glytBotoes")
        self.pbLogin = QtWidgets.QPushButton(self.frPrincipalIteraveis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLogin.sizePolicy().hasHeightForWidth())
        self.pbLogin.setSizePolicy(sizePolicy)
        self.pbLogin.setMinimumSize(QtCore.QSize(170, 50))
        self.pbLogin.setMaximumSize(QtCore.QSize(220, 50))
        self.pbLogin.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbLogin.setFont(font)
        self.pbLogin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbLogin.setMouseTracking(False)
        self.pbLogin.setTabletTracking(False)
        self.pbLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbLogin.setAcceptDrops(False)
        self.pbLogin.setToolTipDuration(-1)
        self.pbLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbLogin.setAutoFillBackground(False)
        self.pbLogin.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    color: rgb(100, 100, 100);\n"
"    background-color: rgb(211, 143, 37);\n"
"    background-color: #DFD880;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcaaa;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbLogin.setIconSize(QtCore.QSize(25, 25))
        self.pbLogin.setCheckable(False)
        self.pbLogin.setChecked(False)
        self.pbLogin.setAutoRepeat(False)
        self.pbLogin.setAutoExclusive(False)
        self.pbLogin.setAutoDefault(False)
        self.pbLogin.setDefault(False)
        self.pbLogin.setFlat(False)
        self.pbLogin.setObjectName("pbLogin")
        self.glytBotoes.addWidget(self.pbLogin, 0, 0, 1, 1)
        self.pbCadastro = QtWidgets.QPushButton(self.frPrincipalIteraveis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCadastro.sizePolicy().hasHeightForWidth())
        self.pbCadastro.setSizePolicy(sizePolicy)
        self.pbCadastro.setMinimumSize(QtCore.QSize(170, 50))
        self.pbCadastro.setMaximumSize(QtCore.QSize(220, 50))
        self.pbCadastro.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbCadastro.setFont(font)
        self.pbCadastro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbCadastro.setMouseTracking(False)
        self.pbCadastro.setTabletTracking(False)
        self.pbCadastro.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbCadastro.setAcceptDrops(False)
        self.pbCadastro.setToolTipDuration(-1)
        self.pbCadastro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbCadastro.setAutoFillBackground(False)
        self.pbCadastro.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    color: rgb(100, 100, 100);\n"
"    background-color: rgb(170, 170, 170);\n"
"    background-color: #80CEE1\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcaaa;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"   background-color: rgb(170, 140, 140);\n"
"}")
        self.pbCadastro.setIconSize(QtCore.QSize(35, 35))
        self.pbCadastro.setCheckable(False)
        self.pbCadastro.setChecked(False)
        self.pbCadastro.setAutoRepeat(False)
        self.pbCadastro.setAutoExclusive(False)
        self.pbCadastro.setAutoDefault(False)
        self.pbCadastro.setDefault(False)
        self.pbCadastro.setFlat(False)
        self.pbCadastro.setObjectName("pbCadastro")
        self.glytBotoes.addWidget(self.pbCadastro, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.glytBotoes, 7, 0, 1, 5)
        self.frLogo = QtWidgets.QFrame(self.frPrincipalIteraveis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frLogo.sizePolicy().hasHeightForWidth())
        self.frLogo.setSizePolicy(sizePolicy)
        self.frLogo.setMinimumSize(QtCore.QSize(305, 182))
        self.frLogo.setMaximumSize(QtCore.QSize(200, 200))
        self.frLogo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frLogo.setAutoFillBackground(False)
        self.frLogo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color:#0E90AD;\n"
"\n"
"border: 20px;\n"
"/*border-image: url(:/newPrefix/002-graduated.png);*/\n"
"/*image: url(:/newPrefix/nautilusIcone.png);*/\n"
"image: url(:/newPrefix/logo-naultilus.png);\n"
"border-radius: 100px\n"
"\n"
"\n"
"")
        self.frLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frLogo.setLineWidth(1)
        self.frLogo.setMidLineWidth(0)
        self.frLogo.setObjectName("frLogo")
        self.gridLayout_3.addWidget(self.frLogo, 5, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frPrincipalIteraveis, 1, 0, 1, 1)
        self.frRedes = QtWidgets.QFrame(self.frBordaIretaveisLogin)
        self.frRedes.setMinimumSize(QtCore.QSize(280, 100))
        self.frRedes.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frRedes.setStyleSheet("")
        self.frRedes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frRedes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frRedes.setObjectName("frRedes")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frRedes)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pbFacebook = QtWidgets.QPushButton(self.frRedes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbFacebook.sizePolicy().hasHeightForWidth())
        self.pbFacebook.setSizePolicy(sizePolicy)
        self.pbFacebook.setMinimumSize(QtCore.QSize(50, 50))
        self.pbFacebook.setMaximumSize(QtCore.QSize(50, 50))
        self.pbFacebook.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbFacebook.setFont(font)
        self.pbFacebook.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbFacebook.setMouseTracking(False)
        self.pbFacebook.setTabletTracking(False)
        self.pbFacebook.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbFacebook.setAcceptDrops(False)
        self.pbFacebook.setToolTipDuration(-1)
        self.pbFacebook.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbFacebook.setAutoFillBackground(False)
        self.pbFacebook.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-image: url(:/newPrefix/043-facebook-1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(135,206,250);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbFacebook.setText("")
        self.pbFacebook.setIconSize(QtCore.QSize(25, 25))
        self.pbFacebook.setCheckable(False)
        self.pbFacebook.setChecked(False)
        self.pbFacebook.setAutoRepeat(False)
        self.pbFacebook.setAutoExclusive(False)
        self.pbFacebook.setAutoDefault(False)
        self.pbFacebook.setDefault(False)
        self.pbFacebook.setFlat(False)
        self.pbFacebook.setObjectName("pbFacebook")
        self.gridLayout_6.addWidget(self.pbFacebook, 0, 0, 1, 1)
        self.pbYouTube = QtWidgets.QPushButton(self.frRedes)
        self.pbYouTube.setMinimumSize(QtCore.QSize(50, 50))
        self.pbYouTube.setMaximumSize(QtCore.QSize(50, 50))
        self.pbYouTube.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbYouTube.setFont(font)
        self.pbYouTube.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbYouTube.setMouseTracking(False)
        self.pbYouTube.setTabletTracking(False)
        self.pbYouTube.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbYouTube.setAcceptDrops(False)
        self.pbYouTube.setToolTipDuration(-1)
        self.pbYouTube.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbYouTube.setAutoFillBackground(False)
        self.pbYouTube.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/002-youtube.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255,182,193);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbYouTube.setText("")
        self.pbYouTube.setIconSize(QtCore.QSize(25, 25))
        self.pbYouTube.setCheckable(False)
        self.pbYouTube.setChecked(False)
        self.pbYouTube.setAutoRepeat(False)
        self.pbYouTube.setAutoExclusive(False)
        self.pbYouTube.setAutoDefault(False)
        self.pbYouTube.setDefault(False)
        self.pbYouTube.setFlat(False)
        self.pbYouTube.setObjectName("pbYouTube")
        self.gridLayout_6.addWidget(self.pbYouTube, 0, 1, 1, 1)
        self.pbTweeter = QtWidgets.QPushButton(self.frRedes)
        self.pbTweeter.setMinimumSize(QtCore.QSize(50, 50))
        self.pbTweeter.setMaximumSize(QtCore.QSize(50, 50))
        self.pbTweeter.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbTweeter.setFont(font)
        self.pbTweeter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbTweeter.setMouseTracking(False)
        self.pbTweeter.setTabletTracking(False)
        self.pbTweeter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbTweeter.setAcceptDrops(False)
        self.pbTweeter.setToolTipDuration(-1)
        self.pbTweeter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbTweeter.setAutoFillBackground(False)
        self.pbTweeter.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"    image: url(:/newPrefix/013-twitter-1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127,255,212);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbTweeter.setText("")
        self.pbTweeter.setIconSize(QtCore.QSize(25, 25))
        self.pbTweeter.setCheckable(False)
        self.pbTweeter.setChecked(False)
        self.pbTweeter.setAutoRepeat(False)
        self.pbTweeter.setAutoExclusive(False)
        self.pbTweeter.setAutoDefault(False)
        self.pbTweeter.setDefault(False)
        self.pbTweeter.setFlat(False)
        self.pbTweeter.setObjectName("pbTweeter")
        self.gridLayout_6.addWidget(self.pbTweeter, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frRedes, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frBordaIretaveisLogin, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 2, 1, 1)
        self.stkLogin.addWidget(self.pgLogin)
        self.gridLayout.addWidget(self.stkLogin, 0, 1, 1, 1)
        mwLogin.setCentralWidget(self.wdgLgin)

        self.retranslateUi(mwLogin)
        QtCore.QMetaObject.connectSlotsByName(mwLogin)

    def retranslateUi(self, mwLogin):
        _translate = QtCore.QCoreApplication.translate
        mwLogin.setWindowTitle(_translate("mwLogin", "MainWindow"))
        self.pbFechaSnackBarLogin.setText(_translate("mwLogin", "X"))
        self.leUsuario.setPlaceholderText(_translate("mwLogin", "Usuário"))
        self.leSenha.setPlaceholderText(_translate("mwLogin", "Senha"))
        self.pbLogin.setText(_translate("mwLogin", "Login"))
        self.pbCadastro.setText(_translate("mwLogin", "Cadastre-se"))
import Telas.login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwLogin = QtWidgets.QMainWindow()
    ui = Ui_mwLogin()
    ui.setupUi(mwLogin)
    mwLogin.show()
    sys.exit(app.exec_())
