# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabFinanceiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabFinanceiroGeral(object):
    def setupUi(self, tabFinanceiroGeral):
        tabFinanceiroGeral.setObjectName("tabFinanceiroGeral")
        tabFinanceiroGeral.resize(1091, 762)
        tabFinanceiroGeral.setStyleSheet("/*#tabFinanceiroGeral {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(86, 158, 139, 255), stop:1 rgba(106, 178, 159, 255));\n"
"}*/\n"
"\n"
"QTabWidget QStackedWidget > QWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(86, 158, 139, 255), stop:1 rgba(106, 178, 159, 255));\n"
"}\n"
"\n"
"#tabFinanceiro::pane { \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(86, 158, 139, 255), stop:1 rgba(106, 178, 159, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 15px; \n"
"}\n"
"\n"
"QTabBar::tab {\n"
"/*    background-color: transparent;*/\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-color: rgb(114, 159, 207);\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(86, 158, 139);\n"
"\n"
"    font-family: Ubuntu;\n"
"    font-size: 18px;\n"
"    color: white;\n"
"\n"
"    border-top-left-radius: 14px;\n"
"    border-top-right-radius: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    font-family: Ubuntu;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; \n"
"    background-color: rgb(61, 79, 69);\n"
"\n"
"    color: white;\n"
"    font-family: Ubuntu;\n"
"    font-size: 12px;\n"
"\n"
"    border-top-left-radius: 11px;\n"
"    border-top-right-radius: 11px;\n"
"}\n"
"\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(tabFinanceiroGeral)
        self.horizontalLayout.setContentsMargins(0, 4, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabFinanceiro = QtWidgets.QTabWidget(tabFinanceiroGeral)
        self.tabFinanceiro.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabFinanceiro.setObjectName("tabFinanceiro")
        self.tabGeral = QtWidgets.QWidget()
        self.tabGeral.setObjectName("tabGeral")
        self.tabFinanceiro.addTab(self.tabGeral, "")
        self.tabPlanos = QtWidgets.QWidget()
        self.tabPlanos.setStyleSheet("/*------------------------------- LineEdit --------------------------------------*/\n"
"#leNomePlano, #leValor {\n"
"    border-top-left-radius: 0px;\n"
"}\n"
"\n"
"\n"
"/*------------------------------- Labels --------------------------------------*/\n"
"#lbDataInicio, \n"
"#lbDataTermino,\n"
"#lbFreq,\n"
"#lbNomePlano,\n"
"#lbValor,\n"
"#lbDescricaoPlano{\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 200;\n"
"    color: rgb(46, 52, 54);\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#lbTituloTabela, #lbTituloCriaPlano {\n"
"    font-family: Ubuntu;\n"
"    font-size: 32px;\n"
"\n"
"    font-weight: 200;\n"
"    color: rgb(46, 52, 54);\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"/*-------------------------------- CheckBox ---------------------------------*/\n"
"#cbPresencial, #cbInativos {\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 200;\n"
"    color: rgb(46, 52, 54);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#cbPresencial::indicator:unchecked, #cbInativos::indicator:unchecked {\n"
"    color: rgb(46, 52, 54);\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"/*--------------------------------- Frames ---------------------------------------*/\n"
"/*QFrame {\n"
"    background-color: transparent;\n"
"}*/\n"
"\n"
"#frTblBottom, #frtblPlanos {\n"
"    /*background-color: transparent;*/\n"
"}\n"
"\n"
"#frCabecalho {\n"
"    background-color: rgb(211, 215, 207);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#frCriaPlanos {\n"
"    background-color: rgba(238, 238, 236, 150);\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/*--------------------------------- Buttons --------------------------------------*/\n"
"#pbInserir {\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    \n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(78, 154, 6);\n"
"\n"
"    color: rgb(46, 52, 54);\n"
"}\n"
"\n"
"#pbInserir:hover {\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    \n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(78, 154, 6);\n"
"\n"
"    color: rgb(46, 52, 54);\n"
"}\n"
"\n"
"#pbCancelar {\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    \n"
"    background-color: rgba(255, 158, 158, 150);\n"
"    border-radius: 4px;\n"
"    border: 1px solid white;\n"
"\n"
"    color: white;\n"
"}\n"
"\n"
"#pbCancelar:hover {\n"
"    font-family: Ubuntu;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    \n"
"    background-color: rgb(225, 128, 128);\n"
"    border-radius: 4px;\n"
"    border: 1px solid white;\n"
"\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"/*---------------------------------- Tables ---------------------------------------*/\n"
"#tblPlanos {\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"    margin-top: 4px;\n"
"}\n"
"\n"
"/*---------------------------------- TextEdit -------------------------------------*/\n"
"#teDescricaoPlano{\n"
"    border-top-left-radius: 0px;\n"
"}")
        self.tabPlanos.setObjectName("tabPlanos")
        self.frtblPlanos = QtWidgets.QFrame(self.tabPlanos)
        self.frtblPlanos.setGeometry(QtCore.QRect(10, 10, 441, 371))
        self.frtblPlanos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frtblPlanos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frtblPlanos.setObjectName("frtblPlanos")
        self.frCabecalho = QtWidgets.QFrame(self.frtblPlanos)
        self.frCabecalho.setGeometry(QtCore.QRect(0, 0, 441, 51))
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.lbTituloTabela = QtWidgets.QLabel(self.frCabecalho)
        self.lbTituloTabela.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.lbTituloTabela.setObjectName("lbTituloTabela")
        self.cbInativos = QtWidgets.QCheckBox(self.frCabecalho)
        self.cbInativos.setGeometry(QtCore.QRect(300, 20, 131, 23))
        self.cbInativos.setObjectName("cbInativos")
        self.frTblBottom = QtWidgets.QFrame(self.frtblPlanos)
        self.frTblBottom.setGeometry(QtCore.QRect(0, 50, 441, 321))
        self.frTblBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTblBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTblBottom.setObjectName("frTblBottom")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frTblBottom)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblPlanos = QtWidgets.QTableWidget(self.frTblBottom)
        self.tblPlanos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblPlanos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblPlanos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblPlanos.setAlternatingRowColors(True)
        self.tblPlanos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblPlanos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblPlanos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tblPlanos.setShowGrid(False)
        self.tblPlanos.setCornerButtonEnabled(False)
        self.tblPlanos.setObjectName("tblPlanos")
        self.tblPlanos.setColumnCount(5)
        self.tblPlanos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblPlanos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPlanos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPlanos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPlanos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPlanos.setHorizontalHeaderItem(4, item)
        self.tblPlanos.horizontalHeader().setCascadingSectionResizes(True)
        self.tblPlanos.horizontalHeader().setHighlightSections(True)
        self.tblPlanos.horizontalHeader().setStretchLastSection(False)
        self.tblPlanos.verticalHeader().setVisible(False)
        self.tblPlanos.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tblPlanos)
        self.frCriaPlanos = QtWidgets.QFrame(self.tabPlanos)
        self.frCriaPlanos.setGeometry(QtCore.QRect(10, 390, 441, 331))
        self.frCriaPlanos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCriaPlanos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCriaPlanos.setObjectName("frCriaPlanos")
        self.lbTituloCriaPlano = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbTituloCriaPlano.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.lbTituloCriaPlano.setObjectName("lbTituloCriaPlano")
        self.lbNomePlano = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbNomePlano.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.lbNomePlano.setObjectName("lbNomePlano")
        self.leNomePlano = QtWidgets.QLineEdit(self.frCriaPlanos)
        self.leNomePlano.setGeometry(QtCore.QRect(10, 90, 141, 25))
        self.leNomePlano.setFrame(False)
        self.leNomePlano.setObjectName("leNomePlano")
        self.lbDataTermino = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbDataTermino.setGeometry(QtCore.QRect(140, 270, 111, 17))
        self.lbDataTermino.setObjectName("lbDataTermino")
        self.lbDataInicio = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbDataInicio.setGeometry(QtCore.QRect(10, 270, 101, 17))
        self.lbDataInicio.setObjectName("lbDataInicio")
        self.lbFreq = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbFreq.setGeometry(QtCore.QRect(10, 200, 71, 17))
        self.lbFreq.setObjectName("lbFreq")
        self.leValor = QtWidgets.QLineEdit(self.frCriaPlanos)
        self.leValor.setGeometry(QtCore.QRect(10, 160, 141, 25))
        self.leValor.setInputMask("")
        self.leValor.setText("")
        self.leValor.setFrame(False)
        self.leValor.setObjectName("leValor")
        self.lbValor = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbValor.setGeometry(QtCore.QRect(10, 140, 41, 17))
        self.lbValor.setObjectName("lbValor")
        self.cbxFreq = QtWidgets.QComboBox(self.frCriaPlanos)
        self.cbxFreq.setGeometry(QtCore.QRect(10, 220, 141, 25))
        self.cbxFreq.setObjectName("cbxFreq")
        self.cbPresencial = QtWidgets.QCheckBox(self.frCriaPlanos)
        self.cbPresencial.setGeometry(QtCore.QRect(330, 20, 90, 23))
        self.cbPresencial.setObjectName("cbPresencial")
        self.dtTermino = QtWidgets.QDateEdit(self.frCriaPlanos)
        self.dtTermino.setGeometry(QtCore.QRect(140, 290, 110, 26))
        self.dtTermino.setDate(QtCore.QDate(2021, 1, 1))
        self.dtTermino.setObjectName("dtTermino")
        self.dtInicio = QtWidgets.QDateEdit(self.frCriaPlanos)
        self.dtInicio.setGeometry(QtCore.QRect(10, 290, 110, 26))
        self.dtInicio.setFrame(True)
        self.dtInicio.setDate(QtCore.QDate(2021, 1, 1))
        self.dtInicio.setObjectName("dtInicio")
        self.teDescricaoPlano = QtWidgets.QTextEdit(self.frCriaPlanos)
        self.teDescricaoPlano.setGeometry(QtCore.QRect(260, 90, 161, 151))
        self.teDescricaoPlano.setObjectName("teDescricaoPlano")
        self.lbDescricaoPlano = QtWidgets.QLabel(self.frCriaPlanos)
        self.lbDescricaoPlano.setGeometry(QtCore.QRect(260, 70, 81, 17))
        self.lbDescricaoPlano.setObjectName("lbDescricaoPlano")
        self.pbInserir = QtWidgets.QPushButton(self.frCriaPlanos)
        self.pbInserir.setGeometry(QtCore.QRect(340, 260, 83, 25))
        self.pbInserir.setObjectName("pbInserir")
        self.pbCancelar = QtWidgets.QPushButton(self.frCriaPlanos)
        self.pbCancelar.setGeometry(QtCore.QRect(340, 290, 83, 25))
        self.pbCancelar.setObjectName("pbCancelar")
        self.tabFinanceiro.addTab(self.tabPlanos, "")
        self.horizontalLayout.addWidget(self.tabFinanceiro)

        self.retranslateUi(tabFinanceiroGeral)
        self.tabFinanceiro.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(tabFinanceiroGeral)

    def retranslateUi(self, tabFinanceiroGeral):
        _translate = QtCore.QCoreApplication.translate
        tabFinanceiroGeral.setWindowTitle(_translate("tabFinanceiroGeral", "tabFinanceiro"))
        self.tabFinanceiro.setTabText(self.tabFinanceiro.indexOf(self.tabGeral), _translate("tabFinanceiroGeral", "Geral"))
        self.lbTituloTabela.setText(_translate("tabFinanceiroGeral", "Planos Ativos"))
        self.cbInativos.setText(_translate("tabFinanceiroGeral", "Mostrar inativos"))
        item = self.tblPlanos.horizontalHeaderItem(0)
        item.setText(_translate("tabFinanceiroGeral", "Id"))
        item = self.tblPlanos.horizontalHeaderItem(1)
        item.setText(_translate("tabFinanceiroGeral", "Nome"))
        item = self.tblPlanos.horizontalHeaderItem(2)
        item.setText(_translate("tabFinanceiroGeral", "Valor"))
        item = self.tblPlanos.horizontalHeaderItem(3)
        item.setText(_translate("tabFinanceiroGeral", "Frequência"))
        item = self.tblPlanos.horizontalHeaderItem(4)
        item.setText(_translate("tabFinanceiroGeral", "Clientes Inscritos"))
        self.lbTituloCriaPlano.setText(_translate("tabFinanceiroGeral", "Criar Plano"))
        self.lbNomePlano.setText(_translate("tabFinanceiroGeral", "Nome do Plano"))
        self.leNomePlano.setPlaceholderText(_translate("tabFinanceiroGeral", "Machado de Assis"))
        self.lbDataTermino.setText(_translate("tabFinanceiroGeral", "Data de término"))
        self.lbDataInicio.setText(_translate("tabFinanceiroGeral", "Data de início"))
        self.lbFreq.setText(_translate("tabFinanceiroGeral", "Frequência"))
        self.lbValor.setText(_translate("tabFinanceiroGeral", "Valor"))
        self.cbPresencial.setText(_translate("tabFinanceiroGeral", "Presencial"))
        self.lbDescricaoPlano.setText(_translate("tabFinanceiroGeral", "Descrição"))
        self.pbInserir.setText(_translate("tabFinanceiroGeral", "INSERIR"))
        self.pbCancelar.setText(_translate("tabFinanceiroGeral", "CANCELAR"))
        self.tabFinanceiro.setTabText(self.tabFinanceiro.indexOf(self.tabPlanos), _translate("tabFinanceiroGeral", "Planos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabFinanceiroGeral = QtWidgets.QWidget()
    ui = Ui_tabFinanceiroGeral()
    ui.setupUi(tabFinanceiroGeral)
    tabFinanceiroGeral.show()
    sys.exit(app.exec_())
