# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwLogin(object):
    def setupUi(self, mwLogin):
        mwLogin.setObjectName("mwLogin")
        mwLogin.setWindowModality(QtCore.Qt.NonModal)
        mwLogin.resize(1006, 800)
        mwLogin.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.163, y1:0.5625, x2:0.888, y2:0.603273, stop:0.0918367 rgba(255, 239, 214, 255), stop:0.55102 rgba(255, 255, 255, 255));")
        mwLogin.setIconSize(QtCore.QSize(25, 25))
        mwLogin.setAnimated(True)
        mwLogin.setDocumentMode(False)
        mwLogin.setTabShape(QtWidgets.QTabWidget.Rounded)
        mwLogin.setDockNestingEnabled(False)
        mwLogin.setUnifiedTitleAndToolBarOnMac(False)
        self.wdgLgin = QtWidgets.QWidget(mwLogin)
        self.wdgLgin.setObjectName("wdgLgin")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wdgLgin)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stkLogin = QtWidgets.QStackedWidget(self.wdgLgin)
        self.stkLogin.setStyleSheet("")
        self.stkLogin.setObjectName("stkLogin")
        self.pgLogin = QtWidgets.QWidget()
        self.pgLogin.setStyleSheet("\n"
"QWidget {\n"
"    background-color: #000000;\n"
"    \n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: rgb(140, 255, 196);\n"
"    background-color: #0E90AD;\n"
"}\n"
"\n"
"")
        self.pgLogin.setObjectName("pgLogin")
        self.frBordaCirculo = QtWidgets.QFrame(self.pgLogin)
        self.frBordaCirculo.setGeometry(QtCore.QRect(430, 20, 500, 500))
        self.frBordaCirculo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frBordaCirculo.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frBordaCirculo.setStyleSheet("QFrame { \n"
"    border-radius: 250px;\n"
"    border: 5px solid #DAA520\n"
"}")
        self.frBordaCirculo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBordaCirculo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBordaCirculo.setObjectName("frBordaCirculo")
        self.frCirculoImputs = QtWidgets.QFrame(self.frBordaCirculo)
        self.frCirculoImputs.setGeometry(QtCore.QRect(50, 50, 400, 400))
        self.frCirculoImputs.setStyleSheet("border-radius: 200px;\n"
"\n"
"")
        self.frCirculoImputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCirculoImputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCirculoImputs.setObjectName("frCirculoImputs")
        self.leUsuario = QtWidgets.QLineEdit(self.frCirculoImputs)
        self.leUsuario.setGeometry(QtCore.QRect(50, 220, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.leUsuario.setFont(font)
        self.leUsuario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leUsuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leUsuario.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(136, 138, 133);\n"
"    border-bottom-color: rgb(136, 138, 133);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.leUsuario.setInputMethodHints(QtCore.Qt.ImhNone)
        self.leUsuario.setInputMask("")
        self.leUsuario.setText("")
        self.leUsuario.setFrame(True)
        self.leUsuario.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.leUsuario.setObjectName("leUsuario")
        self.leSenha = QtWidgets.QLineEdit(self.frCirculoImputs)
        self.leSenha.setGeometry(QtCore.QRect(50, 260, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.leSenha.setFont(font)
        self.leSenha.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leSenha.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(136, 138, 133);\n"
"    border-bottom-color: rgb(136, 138, 133);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.leSenha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.leSenha.setInputMask("")
        self.leSenha.setText("")
        self.leSenha.setFrame(True)
        self.leSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leSenha.setAlignment(QtCore.Qt.AlignCenter)
        self.leSenha.setObjectName("leSenha")
        self.frAvatar = QtWidgets.QFrame(self.frCirculoImputs)
        self.frAvatar.setGeometry(QtCore.QRect(100, 0, 200, 200))
        self.frAvatar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 20px;\n"
"border-image: url(:/newPrefix/Imagens/002-graduated.png);\n"
"border-radius: 100px\n"
"\n"
"\n"
"")
        self.frAvatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frAvatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAvatar.setObjectName("frAvatar")
        self.frLogo = QtWidgets.QFrame(self.pgLogin)
        self.frLogo.setGeometry(QtCore.QRect(50, 150, 131, 171))
        self.frLogo.setStyleSheet("image: url(:/newPrefix/Imagens/nautilusIcone.png);\n"
"image: url(:/newPrefix/Imagens/nautilusIcone.png);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"\n"
"")
        self.frLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frLogo.setObjectName("frLogo")
        self.pbCadastro = QtWidgets.QPushButton(self.pgLogin)
        self.pbCadastro.setGeometry(QtCore.QRect(680, 390, 170, 51))
        self.pbCadastro.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbCadastro.setFont(font)
        self.pbCadastro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbCadastro.setMouseTracking(False)
        self.pbCadastro.setTabletTracking(False)
        self.pbCadastro.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbCadastro.setAcceptDrops(False)
        self.pbCadastro.setToolTipDuration(-1)
        self.pbCadastro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbCadastro.setAutoFillBackground(False)
        self.pbCadastro.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    border: 5px solid #0E90AD;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    border-color:#ffffff;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"")
        self.pbCadastro.setIconSize(QtCore.QSize(35, 35))
        self.pbCadastro.setCheckable(False)
        self.pbCadastro.setChecked(False)
        self.pbCadastro.setAutoRepeat(False)
        self.pbCadastro.setAutoExclusive(False)
        self.pbCadastro.setAutoDefault(False)
        self.pbCadastro.setDefault(False)
        self.pbCadastro.setFlat(False)
        self.pbCadastro.setObjectName("pbCadastro")
        self.pbLogin = QtWidgets.QPushButton(self.pgLogin)
        self.pbLogin.setGeometry(QtCore.QRect(510, 390, 171, 51))
        self.pbLogin.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbLogin.setFont(font)
        self.pbLogin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbLogin.setMouseTracking(False)
        self.pbLogin.setTabletTracking(False)
        self.pbLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbLogin.setAcceptDrops(False)
        self.pbLogin.setToolTipDuration(-1)
        self.pbLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbLogin.setAutoFillBackground(False)
        self.pbLogin.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #FF6961;\n"
"    border: 5px solid #0E90AD;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    border-color:#FF6961;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"")
        self.pbLogin.setIconSize(QtCore.QSize(25, 25))
        self.pbLogin.setCheckable(False)
        self.pbLogin.setChecked(False)
        self.pbLogin.setAutoRepeat(False)
        self.pbLogin.setAutoExclusive(False)
        self.pbLogin.setAutoDefault(False)
        self.pbLogin.setDefault(False)
        self.pbLogin.setFlat(False)
        self.pbLogin.setObjectName("pbLogin")
        self.frGrandeAzul = QtWidgets.QFrame(self.pgLogin)
        self.frGrandeAzul.setGeometry(QtCore.QRect(100, -340, 1000, 1000))
        self.frGrandeAzul.setStyleSheet("QFrame {\n"
"    background-color: #3E5F8A;\n"
"    border-radius: 500px;\n"
"    border: 5px solid #DAA520\n"
"}")
        self.frGrandeAzul.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frGrandeAzul.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frGrandeAzul.setObjectName("frGrandeAzul")
        self.frCirculoImputs_2 = QtWidgets.QFrame(self.pgLogin)
        self.frCirculoImputs_2.setGeometry(QtCore.QRect(20, 140, 200, 200))
        self.frCirculoImputs_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 100px;\n"
"border: 3px solid ;\n"
"")
        self.frCirculoImputs_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frCirculoImputs_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCirculoImputs_2.setObjectName("frCirculoImputs_2")
        self.pbFacebook = QtWidgets.QPushButton(self.pgLogin)
        self.pbFacebook.setGeometry(QtCore.QRect(930, 560, 50, 50))
        self.pbFacebook.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbFacebook.setFont(font)
        self.pbFacebook.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbFacebook.setMouseTracking(False)
        self.pbFacebook.setTabletTracking(False)
        self.pbFacebook.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbFacebook.setAcceptDrops(False)
        self.pbFacebook.setToolTipDuration(-1)
        self.pbFacebook.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbFacebook.setAutoFillBackground(False)
        self.pbFacebook.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"    border-image: url(:/newPrefix/Imagens/043-facebook-1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(135,206,250);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbFacebook.setText("")
        self.pbFacebook.setIconSize(QtCore.QSize(25, 25))
        self.pbFacebook.setCheckable(False)
        self.pbFacebook.setChecked(False)
        self.pbFacebook.setAutoRepeat(False)
        self.pbFacebook.setAutoExclusive(False)
        self.pbFacebook.setAutoDefault(False)
        self.pbFacebook.setDefault(False)
        self.pbFacebook.setFlat(False)
        self.pbFacebook.setObjectName("pbFacebook")
        self.pbYouTube = QtWidgets.QPushButton(self.pgLogin)
        self.pbYouTube.setGeometry(QtCore.QRect(930, 680, 50, 50))
        self.pbYouTube.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbYouTube.setFont(font)
        self.pbYouTube.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbYouTube.setMouseTracking(False)
        self.pbYouTube.setTabletTracking(False)
        self.pbYouTube.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbYouTube.setAcceptDrops(False)
        self.pbYouTube.setToolTipDuration(-1)
        self.pbYouTube.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbYouTube.setAutoFillBackground(False)
        self.pbYouTube.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/Imagens/002-youtube.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255,182,193);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbYouTube.setText("")
        self.pbYouTube.setIconSize(QtCore.QSize(25, 25))
        self.pbYouTube.setCheckable(False)
        self.pbYouTube.setChecked(False)
        self.pbYouTube.setAutoRepeat(False)
        self.pbYouTube.setAutoExclusive(False)
        self.pbYouTube.setAutoDefault(False)
        self.pbYouTube.setDefault(False)
        self.pbYouTube.setFlat(False)
        self.pbYouTube.setObjectName("pbYouTube")
        self.pbTweeter = QtWidgets.QPushButton(self.pgLogin)
        self.pbTweeter.setGeometry(QtCore.QRect(930, 620, 50, 50))
        self.pbTweeter.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pbTweeter.setFont(font)
        self.pbTweeter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbTweeter.setMouseTracking(False)
        self.pbTweeter.setTabletTracking(False)
        self.pbTweeter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbTweeter.setAcceptDrops(False)
        self.pbTweeter.setToolTipDuration(-1)
        self.pbTweeter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbTweeter.setAutoFillBackground(False)
        self.pbTweeter.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/newPrefix/Imagens/013-twitter-1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127,255,212);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 140, 140);\n"
"}\n"
"\n"
"")
        self.pbTweeter.setText("")
        self.pbTweeter.setIconSize(QtCore.QSize(25, 25))
        self.pbTweeter.setCheckable(False)
        self.pbTweeter.setChecked(False)
        self.pbTweeter.setAutoRepeat(False)
        self.pbTweeter.setAutoExclusive(False)
        self.pbTweeter.setAutoDefault(False)
        self.pbTweeter.setDefault(False)
        self.pbTweeter.setFlat(False)
        self.pbTweeter.setObjectName("pbTweeter")
        self.frBarraBaixoAzul = QtWidgets.QFrame(self.pgLogin)
        self.frBarraBaixoAzul.setGeometry(QtCore.QRect(-20, 750, 1051, 50))
        self.frBarraBaixoAzul.setStyleSheet("QFrame {\n"
"    background-color: #3E5F8A;\n"
"    border-radius: 500px;\n"
"    border: 5px solid #DAA520\n"
"}")
        self.frBarraBaixoAzul.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBarraBaixoAzul.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBarraBaixoAzul.setObjectName("frBarraBaixoAzul")
        self.frGrandeAzul.raise_()
        self.frCirculoImputs_2.raise_()
        self.frBordaCirculo.raise_()
        self.frLogo.raise_()
        self.pbCadastro.raise_()
        self.pbLogin.raise_()
        self.pbFacebook.raise_()
        self.pbYouTube.raise_()
        self.pbTweeter.raise_()
        self.frBarraBaixoAzul.raise_()
        self.stkLogin.addWidget(self.pgLogin)
        self.horizontalLayout.addWidget(self.stkLogin)
        mwLogin.setCentralWidget(self.wdgLgin)

        self.retranslateUi(mwLogin)
        self.stkLogin.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mwLogin)

    def retranslateUi(self, mwLogin):
        _translate = QtCore.QCoreApplication.translate
        mwLogin.setWindowTitle(_translate("mwLogin", "MainWindow"))
        self.leUsuario.setPlaceholderText(_translate("mwLogin", "Usuário"))
        self.leSenha.setPlaceholderText(_translate("mwLogin", "Senha"))
        self.pbCadastro.setText(_translate("mwLogin", "Cadastre-se"))
        self.pbLogin.setText(_translate("mwLogin", "Login"))
import resource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwLogin = QtWidgets.QMainWindow()
    ui = Ui_mwLogin()
    ui.setupUi(mwLogin)
    mwLogin.show()
    sys.exit(app.exec_())
